VR Model Viewer: ModelPart Class Reference
ModelPart Class Reference
Represents one node in the model tree and, optionally, one STL mesh.
#include <ModelPart.h>
Classes
struct TransformState
Captures a part transform for undo, redo, and VR synchronisation.
Public Member Functions
ModelPart (const QList< QVariant > &data, ModelPart *parent=nullptr)
Creates a tree node with column data and an optional parent.
~ModelPart ()
Destroys this item and all child items.
void appendChild (ModelPart *item)
Appends a child item to this item.
ModelPart * child (int row)
Returns the child item at a row.
int childCount () const
Counts child items.
int columnCount () const
Counts tree columns stored by this item.
QVariant data (int column) const
Returns data for one tree column.
void set (int column, const QVariant &value)
Replaces data for one tree column.
ModelPart * parentItem ()
Gets this item's parent in the tree.
int row () const
Gets this item's row within its parent.
void removeChild (int row)
Removes and deletes a child item.
void setColour (const unsigned char R, const unsigned char G, const unsigned char B)
Sets the base render colour.
unsigned char getColourR ()
Reads the base red channel.
unsigned char getColourG ()
Reads the base green channel.
unsigned char getColourB ()
Reads the base blue channel.
void setVisible (bool isVisible)
Sets visibility in the tree, desktop renderer, and VR actor.
bool visible ()
Reads the visibility state.
void setScale (double s)
Sets the uniform scale for the desktop and VR actors.
double getScale () const
Reads the uniform scale factor.
void setPosition (double x, double y, double z)
Sets the part translation.
void getPosition (double &x, double &y, double &z) const
Reads the part translation.
void setRotation (double x, double y, double z)
Sets the part rotation.
void getRotation (double &x, double &y, double &z) const
Reads the part rotation.
void setTransformState (const TransformState &state)
Replaces position, rotation, and scale in one operation.
TransformState transformState () const
Captures the current transform.
QString id () const
Gets the stable unique identifier used by VR callbacks.
void setHighlighted (bool highlighted)
Sets transient hover highlighting.
bool highlighted () const
Reads transient hover highlighting.
void setSelectedInView (bool selected)
Sets persistent selection highlighting from the 3D view.
bool selectedInView () const
Reads persistent selection highlighting.
void setGlowEnabled (bool enabled)
Enables or disables glow styling.
bool glowEnabled () const
Reads the glow enable state.
void setGlowColour (const unsigned char R, const unsigned char G, const unsigned char B)
Sets the glow colour.
unsigned char getGlowR () const
Reads the glow red channel.
unsigned char getGlowG () const
Reads the glow green channel.
unsigned char getGlowB () const
Reads the glow blue channel.
void setShrinkFilterActive (bool active)
Legacy helper for directly toggling shrink filter output.
bool isShrinkActive () const
Reads the legacy shrink-active flag.
void setShrinkEnabled (bool enabled)
Stores whether the shrink filter should be used by updatePipeline().
void setClipEnabled (bool enabled)
Stores whether the clip filter should be used by updatePipeline().
void setFilterOrder (int order)
Stores the configured filter execution order.
bool getShrinkEnabled () const
Reads the shrink filter setting.
bool getClipEnabled () const
Reads the clip filter setting.
int getFilterOrder () const
Reads the filter execution order.
void updatePipeline ()
Updates the VTK mapper pipeline from the current filter settings.
void loadSTL (QString fileName)
Loads geometry from an STL file and creates the desktop actor.
bool hasGeometry () const
Checks whether this item owns renderable geometry.
QString filePath () const
Gets the absolute STL file path.
qint64 triangleCount () const
Gets the stored triangle count.
QString summary () const
Builds a short status string for tooltips and the status bar.
vtkSmartPointer< vtkActor > getActor ()
Returns the desktop VTK actor associated with this part.
vtkActor * getNewActor ()
Creates a detached actor for the VR renderer.
void detachVrActor ()
Releases this part's reference to the VR actor after transfer.
vtkSmartPointer< vtkPolyData > createGeometrySnapshot ()
Deep-copies the current filtered geometry for safe cross-thread VR use.
void setGroupName (const QString &name)
Assigns this part to a named group.
QString getGroupName () const
Gets the current group name.
bool isLockedInGroup () const
Checks whether the part is locked into a group.
Private Member Functions
void applyTransformToActors ()
Applies stored transform values to desktop and VR actors.
void refreshAppearance ()
Rebuilds VTK actor material properties from colour, glow, and selection state.
Private Attributes
QList< ModelPart * > m_childItems
Owned child items in the tree hierarchy.
QList< QVariant > m_itemData
Column data displayed by ModelPartList.
ModelPart * m_parentItem
Parent item; nullptr only for the root item.
bool isVisible
Visibility state shared by tree and actors.
unsigned char m_r = 255
Base red colour channel.
unsigned char m_g = 255
Base green colour channel.
unsigned char m_b = 255
Base blue colour channel.
double m_scale = 1.0
Uniform render scale.
double m_position [3] = { 0.0, 0.0, 0.0 }
XYZ translation.
double m_rotation [3] = { 0.0, 0.0, 0.0 }
XYZ Euler rotation in degrees.
QString m_filePath
Absolute path to the loaded STL file.
QString m_id
Stable UUID used to connect desktop and VR updates.
qint64 m_triangleCount = 0
Number of polygons in the STL file.
double m_bounds [6] = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 }
STL bounds in VTK order.
bool m_highlighted = false
True while the mouse is hovering this part.
bool m_selectedInView = false
True when selected from the 3D viewport.
bool m_glowEnabled = false
True when glow material settings are active.
unsigned char m_glowR = 0
Glow red colour channel.
unsigned char m_glowG = 180
Glow green colour channel.
unsigned char m_glowB = 255
Glow blue colour channel.
vtkSmartPointer< vtkSTLReader > file
STL reader that owns the source mesh pipeline.
vtkSmartPointer< vtkPolyDataMapper > mapper
Desktop mapper connected to the active filter pipeline.
vtkSmartPointer< vtkActor > actor
Desktop VTK actor displayed in the main renderer.
vtkSmartPointer< vtkActor > vrActor
Temporary VR actor before ownership is transferred.
vtkSmartPointer< vtkShrinkPolyData > shrinkFilter
Optional shrink filter used for exploded-style previews.
vtkSmartPointer< vtkClipPolyData > clipFilter
Optional clipping filter used to inspect part interiors.
vtkSmartPointer< vtkPlane > clipPlane
Clip plane positioned through the part bounds.
vtkSmartPointer< vtkAlgorithmOutput > originalDataPort
Original STL reader output port.
bool shrinkActive = false
Legacy direct shrink filter state.
bool shrinkEnabled = false
True when updatePipeline() should include shrinkFilter.
bool clipEnabled = false
True when updatePipeline() should include clipFilter.
int filterOrder = 0
Filter order: 0 shrink then clip, 1 clip then shrink.
QString m_groupName = ""
Name of the locked movement group, or empty when ungrouped.
Detailed Description
Represents one node in the model tree and, optionally, one STL mesh.
A ModelPart can act as a purely organisational tree node or as a renderable STL part. Renderable parts own a VTK reader, mapper, actor, optional VR actor, and filter pipeline. Parent and child pointers form the hierarchy consumed by ModelPartList.
Definition at line 38 of file ModelPart.h.
Constructor & Destructor Documentation
ModelPart()
ModelPart::ModelPart (const QList< QVariant > & data, ModelPart * parent = nullptr)
Creates a tree node with column data and an optional parent.
Parameters
data Column values shown in the tree view.
parent Parent tree item, or nullptr for the root item.
Definition at line 27 of file ModelPart.cpp.
References actor, file, isVisible, m_b, m_g, m_id, m_itemData, m_r, and mapper.
~ModelPart()
ModelPart::~ModelPart ()
Destroys this item and all child items.
Definition at line 48 of file ModelPart.cpp.
References m_childItems.
Member Function Documentation
appendChild()
void ModelPart::appendChild (ModelPart * item)
Appends a child item to this item.
Parameters
item Child item to take ownership of.
Definition at line 52 of file ModelPart.cpp.
References m_childItems, and m_parentItem.
Referenced by ModelPartList::appendChild().
applyTransformToActors()
void ModelPart::applyTransformToActors () private
Applies stored transform values to desktop and VR actors.
Definition at line 392 of file ModelPart.cpp.
References actor, m_position, m_rotation, m_scale, row(), and vrActor.
Referenced by getNewActor(), loadSTL(), setPosition(), setRotation(), setScale(), and setTransformState().
child()
ModelPart * ModelPart::child (int row)
Returns the child item at a row.
Parameters
row Child row index.
Returns
Pointer to the child, or nullptr if row is invalid.
Definition at line 57 of file ModelPart.cpp.
References m_childItems, and row().
Referenced by ModelPartList::index().
childCount()
int ModelPart::childCount () const
Counts child items.
Returns
Number of child rows.
Definition at line 63 of file ModelPart.cpp.
References m_childItems.
Referenced by ModelPartList::appendChild(), and ModelPartList::rowCount().
columnCount()
int ModelPart::columnCount () const
Counts tree columns stored by this item.
Returns
Number of columns.
Definition at line 67 of file ModelPart.cpp.
References m_itemData.
Referenced by ModelPartList::columnCount().
createGeometrySnapshot()
vtkSmartPointer< vtkPolyData > ModelPart::createGeometrySnapshot ()
Deep-copies the current filtered geometry for safe cross-thread VR use.
Returns
New polydata snapshot of the current mapper input.
Definition at line 209 of file ModelPart.cpp.
References file, mapper, row(), and updatePipeline().
Referenced by getNewActor().
data()
QVariant ModelPart::data (int column) const
Returns data for one tree column.
Parameters
column Column index.
Returns
Column value, or an invalid QVariant if out of range.
Definition at line 71 of file ModelPart.cpp.
References m_itemData, and row().
Referenced by MainWindow::applyTransformFromControls(), MainWindow::applyTreeFilter(), MainWindow::applyVrColorUpdate(), MainWindow::commitPendingVrTransforms(), ModelPartList::data(), MainWindow::handleButton(), MainWindow::handleTreeClicked(), ModelPartList::headerData(), MainWindow::on_actionDelete_Item_triggered(), and MainWindow::on_actionLock_to_New_Group_triggered().
detachVrActor()
void ModelPart::detachVrActor ()
Releases this part's reference to the VR actor after transfer.
Definition at line 235 of file ModelPart.cpp.
References vrActor.
Referenced by MainWindow::collectActorsForVR().
filePath()
QString ModelPart::filePath () const inline
Gets the absolute STL file path.
Returns
File path, or an empty string for non-geometry tree nodes.
Definition at line 350 of file ModelPart.h.
References m_filePath.
getActor()
vtkSmartPointer< vtkActor > ModelPart::getActor () inline
Returns the desktop VTK actor associated with this part.
Returns
Smart pointer to the actor, or nullptr if no STL is loaded.
Definition at line 368 of file ModelPart.h.
References actor.
Referenced by MainWindow::collectModelBounds(), and MainWindow::updateRenderFromTree().
getClipEnabled()
bool ModelPart::getClipEnabled () const
Reads the clip filter setting.
Returns
True if clipping is enabled.
Definition at line 270 of file ModelPart.cpp.
References clipEnabled.
getColourB()
unsigned char ModelPart::getColourB ()
Reads the base blue channel.
Returns
Blue channel in the range 0-255.
Definition at line 103 of file ModelPart.cpp.
References m_b.
Referenced by MainWindow::cleanupEmptyGroups(), and MainWindow::updateRenderFromTree().
getColourG()
unsigned char ModelPart::getColourG ()
Reads the base green channel.
Returns
Green channel in the range 0-255.
Definition at line 102 of file ModelPart.cpp.
References m_g.
Referenced by MainWindow::cleanupEmptyGroups(), and MainWindow::updateRenderFromTree().
getColourR()
unsigned char ModelPart::getColourR ()
Reads the base red channel.
Returns
Red channel in the range 0-255.
Definition at line 101 of file ModelPart.cpp.
References m_r.
Referenced by MainWindow::cleanupEmptyGroups(), and MainWindow::updateRenderFromTree().
getFilterOrder()
int ModelPart::getFilterOrder () const
Reads the filter execution order.
Returns
0 for shrink-then-clip, 1 for clip-then-shrink.
Definition at line 272 of file ModelPart.cpp.
References filterOrder.
getGlowB()
unsigned char ModelPart::getGlowB () const inline
Reads the glow blue channel.
Returns
Blue channel in the range 0-255.
Definition at line 279 of file ModelPart.h.
References m_glowB.
Referenced by ModelPartList::data().
getGlowG()
unsigned char ModelPart::getGlowG () const inline
Reads the glow green channel.
Returns
Green channel in the range 0-255.
Definition at line 273 of file ModelPart.h.
References m_glowG.
Referenced by ModelPartList::data().
getGlowR()
unsigned char ModelPart::getGlowR () const inline
Reads the glow red channel.
Returns
Red channel in the range 0-255.
Definition at line 267 of file ModelPart.h.
References m_glowR.
Referenced by ModelPartList::data().
getGroupName()
QString ModelPart::getGroupName () const
Gets the current group name.
Returns
Group name, or an empty string if ungrouped.
Definition at line 459 of file ModelPart.cpp.
References m_groupName.
Referenced by MainWindow::cleanupEmptyGroups(), MainWindow::getGroupMembers(), MainWindow::on_itemScaleSlider_valueChanged(), MainWindow::selectedTransformTargets(), and MainWindow::updateRenderFromTree().
getNewActor()
vtkActor * ModelPart::getNewActor ()
Creates a detached actor for the VR renderer.
Returns
Raw VTK actor pointer owned by this ModelPart until detachVrActor().
Definition at line 178 of file ModelPart.cpp.
References actor, applyTransformToActors(), createGeometrySnapshot(), file, refreshAppearance(), row(), and vrActor.
Referenced by MainWindow::collectActorsForVR().
getPosition()
void ModelPart::getPosition (double & x, double & y, double & z) const
Reads the part translation.
Parameters
x Output X position.
y Output Y position.
z Output Z position.
Definition at line 332 of file ModelPart.cpp.
References m_position, and row().
Referenced by MainWindow::syncTransformControls(), and MainWindow::translateModelParts().
getRotation()
void ModelPart::getRotation (double & x, double & y, double & z) const
Reads the part rotation.
Parameters
x Output X rotation in degrees.
y Output Y rotation in degrees.
z Output Z rotation in degrees.
Definition at line 345 of file ModelPart.cpp.
References m_rotation, and row().
Referenced by MainWindow::syncTransformControls().
getScale()
double ModelPart::getScale () const inline
Reads the uniform scale factor.
Returns
Current scale factor.
Definition at line 167 of file ModelPart.h.
References m_scale.
Referenced by MainWindow::cleanupEmptyGroups(), MainWindow::handleTreeClicked(), and MainWindow::syncTransformControls().
getShrinkEnabled()
bool ModelPart::getShrinkEnabled () const
Reads the shrink filter setting.
Returns
True if shrink filtering is enabled.
Definition at line 268 of file ModelPart.cpp.
References shrinkEnabled.
glowEnabled()
bool ModelPart::glowEnabled () const inline
Reads the glow enable state.
Returns
True if glow styling is enabled.
Definition at line 253 of file ModelPart.h.
References m_glowEnabled.
Referenced by ModelPartList::data().
hasGeometry()
bool ModelPart::hasGeometry () const inline
Checks whether this item owns renderable geometry.
Returns
True when an STL file has been loaded.
Definition at line 344 of file ModelPart.h.
References actor, and m_filePath.
Referenced by MainWindow::collectModelBounds(), MainWindow::collectSceneStats(), summary(), and MainWindow::translateModelParts().
highlighted()
bool ModelPart::highlighted () const inline
Reads transient hover highlighting.
Returns
True if highlighted by hover.
Definition at line 229 of file ModelPart.h.
References m_highlighted.
Referenced by ModelPartList::data(), and setHighlighted().
id()
QString ModelPart::id () const inline
Gets the stable unique identifier used by VR callbacks.
Returns
UUID string for this part.
Definition at line 217 of file ModelPart.h.
References m_id.
Referenced by MainWindow::collectActorsForVR(), and MainWindow::findPartByIdRecursive().
isLockedInGroup()
bool ModelPart::isLockedInGroup () const
Checks whether the part is locked into a group.
Returns
True if the group name is not empty.
Definition at line 463 of file ModelPart.cpp.
References m_groupName.
Referenced by MainWindow::on_actionLock_to_New_Group_triggered().
isShrinkActive()
bool ModelPart::isShrinkActive () const inline
Reads the legacy shrink-active flag.
Returns
True if the direct shrink filter path is active.
Definition at line 291 of file ModelPart.h.
References shrinkActive.
loadSTL()
void ModelPart::loadSTL (QString fileName)
Loads geometry from an STL file and creates the desktop actor.
Parameters
fileName Path to the STL file.
Definition at line 124 of file ModelPart.cpp.
References actor, applyTransformToActors(), clipFilter, clipPlane, file, isVisible, m_b, m_bounds, m_filePath, m_g, m_r, m_triangleCount, mapper, originalDataPort, refreshAppearance(), row(), shrinkFilter, and updatePipeline().
Referenced by MainWindow::on_actionOpen_File_triggered(), and MainWindow::on_actionOpen_Folder_triggered().
parentItem()
ModelPart * ModelPart::parentItem ()
Gets this item's parent in the tree.
Returns
Parent item pointer, or nullptr for the root.
Definition at line 83 of file ModelPart.cpp.
References m_parentItem.
Referenced by ModelPartList::parent(), and ModelPartList::removePart().
refreshAppearance()
void ModelPart::refreshAppearance () private
Rebuilds VTK actor material properties from colour, glow, and selection state.
Definition at line 405 of file ModelPart.cpp.
References actor, m_b, m_g, m_glowB, m_glowEnabled, m_glowG, m_glowR, m_highlighted, m_r, m_selectedInView, row(), and vrActor.
Referenced by getNewActor(), loadSTL(), setColour(), setGlowColour(), setGlowEnabled(), setHighlighted(), and setSelectedInView().
removeChild()
void ModelPart::removeChild (int row)
Removes and deletes a child item.
Parameters
row Child row to remove.
Definition at line 240 of file ModelPart.cpp.
References m_childItems, and row().
Referenced by ModelPartList::removePart().
row()
int ModelPart::row () const
Gets this item's row within its parent.
Returns
Row index, or 0 for the root item.
Definition at line 87 of file ModelPart.cpp.
References m_childItems, and m_parentItem.
Referenced by applyTransformToActors(), child(), createGeometrySnapshot(), data(), getNewActor(), getPosition(), getRotation(), loadSTL(), ModelPartList::parent(), refreshAppearance(), removeChild(), ModelPartList::removePart(), set(), setClipEnabled(), setColour(), setFilterOrder(), setGlowColour(), setGlowEnabled(), setGroupName(), setPosition(), setRotation(), setScale(), setSelectedInView(), setShrinkEnabled(), setShrinkFilterActive(), setTransformState(), summary(), transformState(), and updatePipeline().
selectedInView()
bool ModelPart::selectedInView () const inline
Reads persistent selection highlighting.
Returns
True if selected in the 3D view.
Definition at line 241 of file ModelPart.h.
References m_selectedInView.
Referenced by ModelPartList::data().
set()
void ModelPart::set (int column, const QVariant & value)
Replaces data for one tree column.
Parameters
column Column index.
value New column value.
Definition at line 77 of file ModelPart.cpp.
References m_itemData, and row().
Referenced by MainWindow::on_actionOpen_File_triggered(), and ModelPartList::setData().
setClipEnabled()
void ModelPart::setClipEnabled (bool enabled)
Stores whether the clip filter should be used by updatePipeline().
Parameters
enabled True to enable clipping.
Definition at line 264 of file ModelPart.cpp.
References clipEnabled, and row().
setColour()
void ModelPart::setColour (const unsigned char R, const unsigned char G, const unsigned char B)
Sets the base render colour.
Parameters
R Red channel in the range 0-255.
G Green channel in the range 0-255.
B Blue channel in the range 0-255.
Definition at line 93 of file ModelPart.cpp.
References m_b, m_g, m_r, refreshAppearance(), and row().
Referenced by MainWindow::applyVrColorUpdate(), MainWindow::cleanupEmptyGroups(), MainWindow::on_actionAdd_Item_triggered(), and MainWindow::on_actionAdd_Level_triggered().
setFilterOrder()
void ModelPart::setFilterOrder (int order)
Stores the configured filter execution order.
Parameters
order 0 for shrink-then-clip, 1 for clip-then-shrink.
Definition at line 266 of file ModelPart.cpp.
References filterOrder, and row().
setGlowColour()
void ModelPart::setGlowColour (const unsigned char R, const unsigned char G, const unsigned char B)
Sets the glow colour.
Parameters
R Red channel in the range 0-255.
G Green channel in the range 0-255.
B Blue channel in the range 0-255.
Definition at line 385 of file ModelPart.cpp.
References m_glowB, m_glowG, m_glowR, refreshAppearance(), and row().
setGlowEnabled()
void ModelPart::setGlowEnabled (bool enabled)
Enables or disables glow styling.
Parameters
enabled True to enable glow.
Definition at line 380 of file ModelPart.cpp.
References m_glowEnabled, refreshAppearance(), and row().
setGroupName()
void ModelPart::setGroupName (const QString & name)
Assigns this part to a named group.
Parameters
name Group name, or an empty string to clear grouping.
Definition at line 455 of file ModelPart.cpp.
References m_groupName, and row().
Referenced by MainWindow::cleanupEmptyGroups(), MainWindow::on_actionLock_to_New_Group_triggered(), and MainWindow::on_actionUnlock_Item_triggered().
setHighlighted()
void ModelPart::setHighlighted (bool highlighted)
Sets transient hover highlighting.
Parameters
highlighted True when the mouse is hovering this part.
Definition at line 370 of file ModelPart.cpp.
References highlighted(), m_highlighted, and refreshAppearance().
Referenced by MainWindow::setHoveredPart().
setPosition()
void ModelPart::setPosition (double x, double y, double z)
Sets the part translation.
Parameters
x X position in model units.
y Y position in model units.
z Z position in model units.
Definition at line 325 of file ModelPart.cpp.
References applyTransformToActors(), m_position, and row().
Referenced by MainWindow::translateModelParts().
setRotation()
void ModelPart::setRotation (double x, double y, double z)
Sets the part rotation.
Parameters
x Rotation about X in degrees.
y Rotation about Y in degrees.
z Rotation about Z in degrees.
Definition at line 338 of file ModelPart.cpp.
References applyTransformToActors(), m_rotation, and row().
setScale()
void ModelPart::setScale (double s)
Sets the uniform scale for the desktop and VR actors.
Parameters
s Uniform scale factor.
Definition at line 320 of file ModelPart.cpp.
References applyTransformToActors(), m_scale, and row().
Referenced by MainWindow::cleanupEmptyGroups(), and MainWindow::on_itemScaleSlider_valueChanged().
setSelectedInView()
void ModelPart::setSelectedInView (bool selected)
Sets persistent selection highlighting from the 3D view.
Parameters
selected True if selected in the 3D view.
Definition at line 375 of file ModelPart.cpp.
References m_selectedInView, refreshAppearance(), and row().
Referenced by MainWindow::selectViewPart().
setShrinkEnabled()
void ModelPart::setShrinkEnabled (bool enabled)
Stores whether the shrink filter should be used by updatePipeline().
Parameters
enabled True to enable shrink filtering.
Definition at line 262 of file ModelPart.cpp.
References row(), and shrinkEnabled.
setShrinkFilterActive()
void ModelPart::setShrinkFilterActive (bool active)
Legacy helper for directly toggling shrink filter output.
Parameters
active True to connect the shrink filter directly to the mapper.
Definition at line 248 of file ModelPart.cpp.
References mapper, originalDataPort, row(), shrinkActive, and shrinkFilter.
setTransformState()
void ModelPart::setTransformState (const TransformState & state)
Replaces position, rotation, and scale in one operation.
Parameters
state Transform state to apply.
Definition at line 351 of file ModelPart.cpp.
References applyTransformToActors(), m_position, m_rotation, m_scale, and row().
Referenced by MainWindow::applyVrTransformUpdate().
setVisible()
void ModelPart::setVisible (bool isVisible)
Sets visibility in the tree, desktop renderer, and VR actor.
Parameters
isVisible True to show the part.
Definition at line 105 of file ModelPart.cpp.
References actor, isVisible, m_itemData, and vrActor.
Referenced by MainWindow::on_actionAdd_Item_triggered(), MainWindow::on_actionAdd_Level_triggered(), and ModelPartList::setData().
summary()
QString ModelPart::summary () const
Builds a short status string for tooltips and the status bar.
Returns
Human-readable part summary.
Definition at line 467 of file ModelPart.cpp.
References hasGeometry(), m_bounds, m_filePath, m_triangleCount, and row().
Referenced by ModelPartList::data(), MainWindow::handleTreeClicked(), MainWindow::on_actionOpen_File_triggered(), MainWindow::selectViewPart(), and MainWindow::setHoveredPart().
transformState()
ModelPart::TransformState ModelPart::transformState () const
Captures the current transform.
Returns
Current position, rotation, and scale.
Definition at line 362 of file ModelPart.cpp.
References m_position, m_rotation, m_scale, ModelPart::TransformState::position, and row().
Referenced by MainWindow::applyTransformFromControls(), and MainWindow::applyVrTransformUpdate().
triangleCount()
qint64 ModelPart::triangleCount () const inline
Gets the stored triangle count.
Returns
Number of STL polygons counted at load time.
Definition at line 356 of file ModelPart.h.
References m_triangleCount.
Referenced by MainWindow::collectSceneStats().
updatePipeline()
void ModelPart::updatePipeline ()
Updates the VTK mapper pipeline from the current filter settings.
Definition at line 274 of file ModelPart.cpp.
References actor, clipEnabled, clipFilter, file, filterOrder, mapper, row(), shrinkEnabled, and shrinkFilter.
Referenced by createGeometrySnapshot(), and loadSTL().
visible()
bool ModelPart::visible ()
Reads the visibility state.
Returns
True if the part is visible.
Definition at line 120 of file ModelPart.cpp.
References isVisible.
Referenced by MainWindow::collectSceneStats(), ModelPartList::data(), and MainWindow::updateRenderFromTree().
Member Data Documentation
actor
vtkSmartPointer<vtkActor> ModelPart::actor private
Desktop VTK actor displayed in the main renderer.
Definition at line 430 of file ModelPart.h.
Referenced by applyTransformToActors(), getActor(), getNewActor(), hasGeometry(), loadSTL(), ModelPart(), refreshAppearance(), setVisible(), and updatePipeline().
clipEnabled
bool ModelPart::clipEnabled = false private
True when updatePipeline() should include clipFilter.
Definition at line 440 of file ModelPart.h.
Referenced by getClipEnabled(), setClipEnabled(), and updatePipeline().
clipFilter
vtkSmartPointer<vtkClipPolyData> ModelPart::clipFilter private
Optional clipping filter used to inspect part interiors.
Definition at line 434 of file ModelPart.h.
Referenced by loadSTL(), and updatePipeline().
clipPlane
vtkSmartPointer<vtkPlane> ModelPart::clipPlane private
Clip plane positioned through the part bounds.
Definition at line 435 of file ModelPart.h.
Referenced by loadSTL().
file
vtkSmartPointer<vtkSTLReader> ModelPart::file private
STL reader that owns the source mesh pipeline.
Definition at line 428 of file ModelPart.h.
Referenced by createGeometrySnapshot(), getNewActor(), loadSTL(), ModelPart(), and updatePipeline().
filterOrder
int ModelPart::filterOrder = 0 private
Filter order: 0 shrink then clip, 1 clip then shrink.
Definition at line 441 of file ModelPart.h.
Referenced by getFilterOrder(), setFilterOrder(), and updatePipeline().
isVisible
bool ModelPart::isVisible private
Visibility state shared by tree and actors.
Definition at line 410 of file ModelPart.h.
Referenced by loadSTL(), ModelPart(), setVisible(), and visible().
m_b
unsigned char ModelPart::m_b = 255 private
Base blue colour channel.
Definition at line 413 of file ModelPart.h.
Referenced by getColourB(), loadSTL(), ModelPart(), refreshAppearance(), and setColour().
m_bounds
double ModelPart::m_bounds[6] = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 } private
STL bounds in VTK order.
Definition at line 420 of file ModelPart.h.
Referenced by loadSTL(), and summary().
m_childItems
QList<ModelPart*> ModelPart::m_childItems private
Owned child items in the tree hierarchy.
Definition at line 406 of file ModelPart.h.
Referenced by appendChild(), child(), childCount(), removeChild(), row(), and ~ModelPart().
m_filePath
QString ModelPart::m_filePath private
Absolute path to the loaded STL file.
Definition at line 417 of file ModelPart.h.
Referenced by filePath(), hasGeometry(), loadSTL(), and summary().
m_g
unsigned char ModelPart::m_g = 255 private
Base green colour channel.
Definition at line 412 of file ModelPart.h.
Referenced by getColourG(), loadSTL(), ModelPart(), refreshAppearance(), and setColour().
m_glowB
unsigned char ModelPart::m_glowB = 255 private
Glow blue colour channel.
Definition at line 426 of file ModelPart.h.
Referenced by getGlowB(), refreshAppearance(), and setGlowColour().
m_glowEnabled
bool ModelPart::m_glowEnabled = false private
True when glow material settings are active.
Definition at line 423 of file ModelPart.h.
Referenced by glowEnabled(), refreshAppearance(), and setGlowEnabled().
m_glowG
unsigned char ModelPart::m_glowG = 180 private
Glow green colour channel.
Definition at line 425 of file ModelPart.h.
Referenced by getGlowG(), refreshAppearance(), and setGlowColour().
m_glowR
unsigned char ModelPart::m_glowR = 0 private
Glow red colour channel.
Definition at line 424 of file ModelPart.h.
Referenced by getGlowR(), refreshAppearance(), and setGlowColour().
m_groupName
QString ModelPart::m_groupName = "" private
Name of the locked movement group, or empty when ungrouped.
Definition at line 443 of file ModelPart.h.
Referenced by getGroupName(), isLockedInGroup(), and setGroupName().
m_highlighted
bool ModelPart::m_highlighted = false private
True while the mouse is hovering this part.
Definition at line 421 of file ModelPart.h.
Referenced by highlighted(), refreshAppearance(), and setHighlighted().
m_id
QString ModelPart::m_id private
Stable UUID used to connect desktop and VR updates.
Definition at line 418 of file ModelPart.h.
Referenced by id(), and ModelPart().
m_itemData
QList<QVariant> ModelPart::m_itemData private
Column data displayed by ModelPartList.
Definition at line 407 of file ModelPart.h.
Referenced by columnCount(), data(), ModelPart(), set(), and setVisible().
m_parentItem
ModelPart* ModelPart::m_parentItem private
Parent item; nullptr only for the root item.
Definition at line 408 of file ModelPart.h.
Referenced by appendChild(), parentItem(), and row().
m_position
double ModelPart::m_position[3] = { 0.0, 0.0, 0.0 } private
XYZ translation.
Definition at line 415 of file ModelPart.h.
Referenced by applyTransformToActors(), getPosition(), setPosition(), setTransformState(), and transformState().
m_r
unsigned char ModelPart::m_r = 255 private
Base red colour channel.
Definition at line 411 of file ModelPart.h.
Referenced by getColourR(), loadSTL(), ModelPart(), refreshAppearance(), and setColour().
m_rotation
double ModelPart::m_rotation[3] = { 0.0, 0.0, 0.0 } private
XYZ Euler rotation in degrees.
Definition at line 416 of file ModelPart.h.
Referenced by applyTransformToActors(), getRotation(), setRotation(), setTransformState(), and transformState().
m_scale
double ModelPart::m_scale = 1.0 private
Uniform render scale.
Definition at line 414 of file ModelPart.h.
Referenced by applyTransformToActors(), getScale(), setScale(), setTransformState(), and transformState().
m_selectedInView
bool ModelPart::m_selectedInView = false private
True when selected from the 3D viewport.
Definition at line 422 of file ModelPart.h.
Referenced by refreshAppearance(), selectedInView(), and setSelectedInView().
m_triangleCount
qint64 ModelPart::m_triangleCount = 0 private
Number of polygons in the STL file.
Definition at line 419 of file ModelPart.h.
Referenced by loadSTL(), summary(), and triangleCount().
mapper
vtkSmartPointer<vtkPolyDataMapper> ModelPart::mapper private
Desktop mapper connected to the active filter pipeline.
Definition at line 429 of file ModelPart.h.
Referenced by createGeometrySnapshot(), loadSTL(), ModelPart(), setShrinkFilterActive(), and updatePipeline().
originalDataPort
vtkSmartPointer<vtkAlgorithmOutput> ModelPart::originalDataPort private
Original STL reader output port.
Definition at line 436 of file ModelPart.h.
Referenced by loadSTL(), and setShrinkFilterActive().
shrinkActive
bool ModelPart::shrinkActive = false private
Legacy direct shrink filter state.
Definition at line 438 of file ModelPart.h.
Referenced by isShrinkActive(), and setShrinkFilterActive().
shrinkEnabled
bool ModelPart::shrinkEnabled = false private
True when updatePipeline() should include shrinkFilter.
Definition at line 439 of file ModelPart.h.
Referenced by getShrinkEnabled(), setShrinkEnabled(), and updatePipeline().
shrinkFilter
vtkSmartPointer<vtkShrinkPolyData> ModelPart::shrinkFilter private
Optional shrink filter used for exploded-style previews.
Definition at line 433 of file ModelPart.h.
Referenced by loadSTL(), setShrinkFilterActive(), and updatePipeline().
vrActor
vtkSmartPointer<vtkActor> ModelPart::vrActor private
Temporary VR actor before ownership is transferred.
Definition at line 431 of file ModelPart.h.
Referenced by applyTransformToActors(), detachVrActor(), getNewActor(), refreshAppearance(), and setVisible().
The documentation for this class was generated from the following files:
ModelPart.h
ModelPart.cpp