VR Model Viewer: MainWindow Class Reference
MainWindow Class Reference
Primary application window for loading, editing, rendering, and viewing STL assemblies in VR.
#include <mainwindow.h>
Public Slots
void handleButton ()
Adds a new child item under the selected tree item.
void handleTreeClicked ()
Handles tree selection changes and synchronises the 3D selection state.
void on_actionOpen_File_triggered ()
Opens one STL file and loads it into the selected or new tree item.
void on_actionOpen_Folder_triggered ()
Opens a folder and loads all discovered STL files into the tree.
void on_actionItemOptions_triggered ()
Opens the Part Options dialog for the selected part.
void on_actionAdd_Level_triggered ()
Adds an empty top-level tree item.
void on_actionAdd_Item_triggered ()
Adds an empty child item under the current selection.
void on_actionDelete_Item_triggered ()
Deletes the selected tree item after confirmation.
Signals
void statusUpdateMessage (const QString &message, int timeout)
Requests a status-bar message.
Public Member Functions
MainWindow (QWidget *parent=nullptr)
Creates the application window, model, renderer, and custom controls.
~MainWindow ()
Stops VR if needed and releases UI/model resources.
Private Slots
void updateRender ()
Rebuilds the desktop scene without resetting the camera.
void updateRenderFromTree (const QModelIndex &index, QMap< QString, vtkSmartPointer< vtkAssembly > > &assemblies)
Recursively adds visible actors from the tree into the VTK scene.
void on_actionToggle_Filter_triggered ()
Toggles whether hidden parts are removed from the renderer.
void on_lightSlider_valueChanged (int value)
Updates the scene light intensity from the UI slider.
void on_zoomSlider_valueChanged (int value)
Updates the desktop camera zoom from the UI slider.
void on_itemScaleSlider_valueChanged (int value)
Updates selected part or group scale from the UI slider.
void handleSearchTextChanged (const QString &text)
Filters the tree view by search text.
void applyTransformFromControls ()
Applies transform spin-box values to selected parts.
void resetSelectedTransform ()
Resets selected part transforms to identity.
void applyEnvironmentSelection (int index)
Applies the currently selected HDR environment.
void on_actionStart_VR_triggered ()
Starts the VR render thread and transfers actor snapshots.
void on_actionStop_VR_triggered ()
Stops the VR render thread.
void on_actionPause_VR_triggered ()
Pauses or resumes VR animation.
void on_actionLock_to_New_Group_triggered ()
Locks selected parts into a new movement group.
void on_actionUnlock_Item_triggered ()
Removes selected parts from their movement group.
void cleanupEmptyGroups ()
Removes group tree entries that no longer contain any parts.
Private Member Functions
QList< ModelPart * > getGroupMembers (const QModelIndex &parentIndex, const QString &groupName)
Finds all parts assigned to a group.
QModelIndex normalizedTreeIndex (const QModelIndex &index) const
Converts any tree index to its column-0 equivalent.
void setupProfessionalUi ()
Builds the professional dark UI around the generated widgets.
void setupRenderingPipeline ()
Creates the desktop VTK renderer, render window, pickers, and callbacks.
void configureActions ()
Configures toolbar/menu text, icons, and action states.
void rebuildScene (bool resetCamera)
Rebuilds all desktop scene props from the current model state.
void fitCameraToScene ()
Fits the desktop camera to the loaded scene.
void addPersistentSceneProps ()
Adds grid, skybox, and orientation props that are independent of model parts.
void createGridActor ()
Creates or recreates the floor grid actor.
void populateHdrOptions ()
Populates the HDR combo box with built-in and remembered environments.
void importHdrFile ()
Imports a user-selected HDR file into the environment selector.
void applyTreeScale (int value)
Applies a scaling value to the tree view UI.
void applyPerformanceMode (bool enabled)
Applies rendering settings for high-performance or higher-quality mode.
void applyVrTuningToThread ()
Sends current VR tuning values to an active VR thread.
void applyEnvironmentOrientation ()
Applies HDR orientation controls to desktop and VR environments.
bool applyTreeFilter (const QModelIndex &parentIndex, const QString &filterText)
Recursively filters tree rows by text.
void updateSceneSummary ()
Recalculates scene statistics and updates the status label.
void collectSceneStats (const QModelIndex &parentIndex, int &loadedParts, int &visibleParts, qint64 &triangles) const
Recursively counts loaded parts, visible parts, and triangles.
bool collectModelBounds (const QModelIndex &parentIndex, double bounds[6]) const
Recursively calculates combined model bounds.
void centerModelAtOrigin (const QModelIndex &parentIndex)
Translates a set of model parts so their combined centre sits at the origin.
void translateModelParts (const QModelIndex &parentIndex, double dx, double dy, double dz)
Recursively translates model parts by a delta.
void stopVRThread ()
Safely stops and deletes the VR thread if it exists.
QList< ModelPart * > selectedTransformTargets () const
Gets the current transform targets, expanding groups when needed.
void syncTransformControls (ModelPart *part)
Copies a part transform into the transform spin boxes.
void applyTransformStates (const QList< ModelPart * > &parts, const QVector< ModelPart::TransformState > &states)
Applies a list of transform states to matching parts.
void setHoveredPart (ModelPart *part)
Updates hover highlighting in the tree and 3D view.
void selectViewPart (ModelPart *part)
Selects a part from the desktop 3D view and synchronises the tree.
QModelIndex findIndexForPart (ModelPart *part) const
Finds the tree index for a ModelPart pointer.
QModelIndex findIndexForPartRecursive (const QModelIndex &parentIndex, ModelPart *part) const
Recursive implementation of findIndexForPart().
ModelPart * findPartById (const QString &id) const
Finds a part by its stable id.
ModelPart * findPartByIdRecursive (const QModelIndex &parentIndex, const QString &id) const
Recursive implementation of findPartById().
void handleVtkHoverEvent ()
Handles a VTK mouse-move callback and updates hover highlighting.
void handleVtkClickEvent ()
Handles a VTK left-click callback and selects the picked part.
void applyVrTransformUpdate (const QString &partId, double px, double py, double pz, double rx, double ry, double rz, double scale)
Applies a transform update received from VR.
void applyVrColorUpdate (const QString &partId, int r, int g, int b)
Applies a colour update received from a VR controller action.
void commitPendingVrTransforms ()
Converts debounced VR movement into undo-stack commands.
void resetVrView ()
Resets the active VR view using current UI tuning controls.
void collectActorsForVR (const QModelIndex &index)
Recursively collects detached actor snapshots for the VR renderer.
Private Attributes
Ui::MainWindow * ui
Generated widget tree from mainwindow.ui.
ModelPartList * partList
Qt model containing all loaded ModelPart items.
QLineEdit * searchEdit = nullptr
Search box used to filter the tree view.
QComboBox * hdrComboBox = nullptr
Environment selector for built-in and imported HDR files.
QPushButton * importHdrButton = nullptr
Button that imports a custom HDR file.
QComboBox * vrViewModeCombo = nullptr
Standing/sitting VR mode selector.
QComboBox * vrViewAngleCombo = nullptr
Preset camera yaw selector for VR reset.
QDoubleSpinBox * hdrTiltSpin = nullptr
HDR X tilt control in degrees.
QDoubleSpinBox * hdrTiltYSpin = nullptr
HDR Y tilt control in degrees.
QDoubleSpinBox * hdrHeadingSpin = nullptr
HDR heading control in degrees.
QDoubleSpinBox * vrModelSizeSpin = nullptr
Target model size in VR metres.
QDoubleSpinBox * vrDistanceSpin = nullptr
VR reset-view standoff distance.
QDoubleSpinBox * vrHeightOffsetSpin = nullptr
VR headset height fine-tuning offset.
QLabel * sceneStatsLabel = nullptr
Status bar label showing scene totals.
QLabel * selectionDetailsLabel = nullptr
Status bar label showing selected part details.
QProgressBar * loadProgressBar = nullptr
Progress indicator for bulk STL loading.
QTimer * vrTransformCommitTimer = nullptr
Debounces VR move updates into one undo command.
QSlider * treeScaleSlider = nullptr
UI control that scales the tree view font and row size.
QDoubleSpinBox * positionSpin [3] = { nullptr, nullptr, nullptr }
XYZ position controls.
QDoubleSpinBox * rotationSpin [3] = { nullptr, nullptr, nullptr }
XYZ rotation controls.
QDoubleSpinBox * transformScaleSpin = nullptr
Uniform transform scale control.
QPushButton * applyTransformButton = nullptr
Button that applies transform spin-box values.
QPushButton * resetTransformButton = nullptr
Button that resets selected transform values.
QPushButton * resetVrViewButton = nullptr
Button that resets the headset view pose.
QSplitter * mainSplitter = nullptr
Main left/view/right splitter that makes panels resizable.
QUndoStack * undoStack = nullptr
Undo/redo stack for transforms and VR moves.
QAction * gridAction = nullptr
Toolbar action that toggles the floor grid.
QAction * performanceAction = nullptr
Toolbar action that toggles high-performance rendering mode.
QAction * showcaseSpinAction = nullptr
Toolbar action that toggles automatic showcase rotation.
bool visibilityFilterOn = false
True when hidden parts are excluded from the renderer.
bool bulkLoading = false
True while loading many STL files to suppress expensive updates.
int hoverPickIntervalMs = 55
Minimum delay between hover-picking operations.
QElapsedTimer hoverPickTimer
Timer used to throttle desktop hover picking.
QElapsedTimer vrTransformRenderTimer
Timer used to throttle desktop redraws from VR movement.
QHash< QString, ModelPart::TransformState > pendingVrTransformStartStates
Original transforms for pending VR undo commands.
QHash< QString, ModelPart::TransformState > pendingVrTransformLatestStates
Latest transforms received from VR before commit.
vtkSmartPointer< vtkRenderer > renderer
Desktop VTK renderer.
vtkSmartPointer< vtkGenericOpenGLRenderWindow > renderWindow
Qt-compatible OpenGL render window.
vtkSmartPointer< vtkSkybox > mySkybox
Desktop skybox actor for HDR environments.
vtkSmartPointer< vtkOrientationMarkerWidget > orientationMarker
Small orientation axes widget.
vtkSmartPointer< vtkActor > gridActor
Floor grid actor.
vtkSmartPointer< vtkActor > environmentActor
Legacy environment actor placeholder.
vtkSmartPointer< vtkTexture > environmentTexture
Desktop HDR environment texture.
vtkSmartPointer< vtkImageData > environmentBaseImage
Tonemapped HDR image before orientation.
vtkSmartPointer< vtkImageData > environmentImage
Oriented HDR image currently displayed.
vtkSmartPointer< vtkPropPicker > propPicker
Picker used for hover and click selection.
vtkSmartPointer< vtkCallbackCommand > mouseMoveCallback
VTK callback for hover events.
vtkSmartPointer< vtkCallbackCommand > leftClickCallback
VTK callback for click selection.
QMap< QString, vtkSmartPointer< vtkAssembly > > groupAssemblies
Group-name to VTK assembly map.
QHash< vtkActor *, ModelPart * > actorPartMap
Desktop actor to ModelPart lookup table.
ModelPart * hoveredPart = nullptr
Part currently highlighted by hover.
ModelPart * selectedViewPart = nullptr
Part currently selected in the 3D view.
VRRenderThread * vrThread = nullptr
Active VR worker thread, or nullptr when VR is stopped.
Detailed Description
Primary application window for loading, editing, rendering, and viewing STL assemblies in VR.
The class owns the desktop VTK scene and the Qt controls around it. It loads STL files into a ModelPartList tree, applies per-part materials and filters, manages grouping and transforms, and starts/stops VRRenderThread for the headset view.
Definition at line 64 of file mainwindow.h.
Constructor & Destructor Documentation
MainWindow()
MainWindow::MainWindow (QWidget * parent = nullptr)
Creates the application window, model, renderer, and custom controls.
Parameters
parent Optional parent widget.
Definition at line 416 of file mainwindow.cpp.
References bulkLoading, configureActions(), handleButton(), handleSearchTextChanged(), handleTreeClicked(), on_actionItemOptions_triggered(), partList, searchEdit, setupProfessionalUi(), setupRenderingPipeline(), statusUpdateMessage(), syncTransformControls(), ui, undoStack, updateRender(), and updateSceneSummary().
~MainWindow()
MainWindow::~MainWindow ()
Stops VR if needed and releases UI/model resources.
Definition at line 470 of file mainwindow.cpp.
References stopVRThread(), and ui.
Member Function Documentation
addPersistentSceneProps()
void MainWindow::addPersistentSceneProps () private
Adds grid, skybox, and orientation props that are independent of model parts.
Definition at line 1007 of file mainwindow.cpp.
References environmentActor, gridAction, gridActor, mySkybox, and renderer.
Referenced by rebuildScene(), and setupRenderingPipeline().
applyEnvironmentOrientation()
void MainWindow::applyEnvironmentOrientation () private
Applies HDR orientation controls to desktop and VR environments.
Definition at line 1163 of file mainwindow.cpp.
References environmentBaseImage, environmentImage, environmentTexture, hdrHeadingSpin, hdrTiltSpin, hdrTiltYSpin, mySkybox, renderer, renderWindow, VRRenderThread::setEnvironmentOrientation(), and vrThread.
Referenced by applyEnvironmentSelection(), setupProfessionalUi(), and setupRenderingPipeline().
applyEnvironmentSelection
void MainWindow::applyEnvironmentSelection (int index) private slot
Applies the currently selected HDR environment.
Parameters
index Combo-box index of the selected environment.
Definition at line 1095 of file mainwindow.cpp.
References applyEnvironmentOrientation(), environmentActor, environmentBaseImage, environmentImage, environmentTexture, hdrComboBox, mySkybox, rebuildScene(), renderer, VRRenderThread::setEnvironmentPath(), statusUpdateMessage(), and vrThread.
Referenced by setupRenderingPipeline().
applyPerformanceMode()
void MainWindow::applyPerformanceMode (bool enabled) private
Applies rendering settings for high-performance or higher-quality mode.
Parameters
enabled True to prefer performance.
Definition at line 1262 of file mainwindow.cpp.
References hoverPickIntervalMs, renderWindow, and ui.
Referenced by configureActions(), and setupRenderingPipeline().
applyTransformFromControls
void MainWindow::applyTransformFromControls () private slot
Applies transform spin-box values to selected parts.
Definition at line 1495 of file mainwindow.cpp.
References ModelPart::data(), ModelPart::TransformState::position, positionSpin, ModelPart::TransformState::rotation, rotationSpin, ModelPart::TransformState::scale, selectedTransformTargets(), selectedViewPart, transformScaleSpin, ModelPart::transformState(), and undoStack.
Referenced by resetSelectedTransform(), and setupProfessionalUi().
applyTransformStates()
void MainWindow::applyTransformStates (const QList< ModelPart * > & parts, const QVector< ModelPart::TransformState > & states) private
Applies a list of transform states to matching parts.
Parameters
parts Parts to update.
states Transform states aligned with parts.
Definition at line 1482 of file mainwindow.cpp.
References renderer, renderWindow, selectedViewPart, and syncTransformControls().
applyTreeFilter()
bool MainWindow::applyTreeFilter (const QModelIndex & parentIndex, const QString & filterText) private
Recursively filters tree rows by text.
Parameters
parentIndex Parent index to search below.
filterText Lowercase text to match.
Returns
True when parent or any child should remain visible.
Definition at line 1291 of file mainwindow.cpp.
References applyTreeFilter(), ModelPart::data(), ModelPartList::index(), partList, ModelPartList::rowCount(), and ui.
Referenced by applyTreeFilter(), and handleSearchTextChanged().
applyTreeScale()
void MainWindow::applyTreeScale (int value) private
Applies a scaling value to the tree view UI.
Parameters
value Slider value interpreted as percentage.
Definition at line 1248 of file mainwindow.cpp.
References ui.
Referenced by setupProfessionalUi().
applyVrColorUpdate()
void MainWindow::applyVrColorUpdate (const QString & partId, int r, int g, int b) private
Applies a colour update received from a VR controller action.
Parameters
partId Stable ModelPart identifier.
r Red channel.
g Green channel.
b Blue channel.
Definition at line 1771 of file mainwindow.cpp.
References ModelPart::data(), findIndexForPart(), findPartById(), partList, renderWindow, ModelPart::setColour(), and statusUpdateMessage().
Referenced by on_actionStart_VR_triggered().
applyVrTransformUpdate()
void MainWindow::applyVrTransformUpdate (const QString & partId, double px, double py, double pz, double rx, double ry, double rz, double scale) private
Applies a transform update received from VR.
Parameters
partId Stable ModelPart identifier.
px New X position.
py New Y position.
pz New Z position.
rx New X rotation in degrees.
ry New Y rotation in degrees.
rz New Z rotation in degrees.
scale New uniform scale.
Definition at line 1682 of file mainwindow.cpp.
References findPartById(), pendingVrTransformLatestStates, pendingVrTransformStartStates, ModelPart::TransformState::position, renderer, renderWindow, ModelPart::TransformState::rotation, ModelPart::TransformState::scale, selectedViewPart, ModelPart::setTransformState(), syncTransformControls(), ModelPart::transformState(), vrTransformCommitTimer, and vrTransformRenderTimer.
Referenced by on_actionStart_VR_triggered().
applyVrTuningToThread()
void MainWindow::applyVrTuningToThread () private
Sends current VR tuning values to an active VR thread.
Definition at line 1278 of file mainwindow.cpp.
References VRRenderThread::setViewTuning(), vrDistanceSpin, vrHeightOffsetSpin, vrModelSizeSpin, and vrThread.
Referenced by setupProfessionalUi().
centerModelAtOrigin()
void MainWindow::centerModelAtOrigin (const QModelIndex & parentIndex) private
Translates a set of model parts so their combined centre sits at the origin.
Parameters
parentIndex Parent index defining the subtree to centre.
Definition at line 1404 of file mainwindow.cpp.
References collectModelBounds(), and translateModelParts().
Referenced by on_actionOpen_File_triggered(), and on_actionOpen_Folder_triggered().
cleanupEmptyGroups
void MainWindow::cleanupEmptyGroups () private slot
Removes group tree entries that no longer contain any parts.
Definition at line 2552 of file mainwindow.cpp.
References ModelPart::getColourB(), ModelPart::getColourG(), ModelPart::getColourR(), ModelPart::getGroupName(), ModelPart::getScale(), ModelPart::setColour(), ModelPart::setGroupName(), ModelPart::setScale(), ui, and updateRender().
Referenced by on_actionUnlock_Item_triggered().
collectActorsForVR()
void MainWindow::collectActorsForVR (const QModelIndex & index) private
Recursively collects detached actor snapshots for the VR renderer.
Parameters
index Tree index at which to start recursion.
Definition at line 2316 of file mainwindow.cpp.
References VRRenderThread::addActorOffline(), collectActorsForVR(), ModelPart::detachVrActor(), ModelPart::getNewActor(), ModelPart::id(), ModelPartList::index(), partList, ModelPartList::rowCount(), and vrThread.
Referenced by collectActorsForVR(), and on_actionStart_VR_triggered().
collectModelBounds()
bool MainWindow::collectModelBounds (const QModelIndex & parentIndex, double bounds[6]) const private
Recursively calculates combined model bounds.
Parameters
parentIndex Parent index to measure below.
bounds Output VTK bounds array.
Returns
True if at least one geometry part contributed bounds.
Definition at line 1340 of file mainwindow.cpp.
References collectModelBounds(), ModelPart::getActor(), ModelPart::hasGeometry(), ModelPartList::index(), partList, and ModelPartList::rowCount().
Referenced by centerModelAtOrigin(), collectModelBounds(), on_actionStart_VR_triggered(), and resetVrView().
collectSceneStats()
void MainWindow::collectSceneStats (const QModelIndex & parentIndex, int & loadedParts, int & visibleParts, qint64 & triangles) const private
Recursively counts loaded parts, visible parts, and triangles.
Parameters
parentIndex Parent index to count below.
loadedParts Output count of parts with geometry.
visibleParts Output count of visible geometry parts.
triangles Output total triangle count.
Definition at line 1321 of file mainwindow.cpp.
References collectSceneStats(), ModelPart::hasGeometry(), ModelPartList::index(), partList, ModelPartList::rowCount(), ModelPart::triangleCount(), and ModelPart::visible().
Referenced by collectSceneStats(), on_actionStart_VR_triggered(), and updateSceneSummary().
commitPendingVrTransforms()
void MainWindow::commitPendingVrTransforms () private
Converts debounced VR movement into undo-stack commands.
Definition at line 1729 of file mainwindow.cpp.
References ModelPart::data(), findPartById(), pendingVrTransformLatestStates, pendingVrTransformStartStates, ModelPart::TransformState::position, ModelPart::TransformState::rotation, ModelPart::TransformState::scale, and undoStack.
Referenced by setupProfessionalUi(), and stopVRThread().
configureActions()
void MainWindow::configureActions () private
Configures toolbar/menu text, icons, and action states.
Definition at line 753 of file mainwindow.cpp.
References applyPerformanceMode(), fitCameraToScene(), gridAction, gridActor, hoveredPart, ModelPartList::index(), VRRenderThread::issueCommand(), mainSplitter, normalizedTreeIndex(), on_actionUnlock_Item_triggered(), partList, performanceAction, rebuildScene(), ModelPartList::removePart(), renderWindow, ModelPartList::rowCount(), selectedViewPart, selectionDetailsLabel, VRRenderThread::SET_SHOWCASE_SPIN, showcaseSpinAction, statusUpdateMessage(), syncTransformControls(), ui, undoStack, updateSceneSummary(), visibilityFilterOn, and vrThread.
Referenced by MainWindow().
createGridActor()
void MainWindow::createGridActor () private
Creates or recreates the floor grid actor.
Definition at line 967 of file mainwindow.cpp.
References gridActor.
Referenced by setupRenderingPipeline().
findIndexForPart()
QModelIndex MainWindow::findIndexForPart (ModelPart * part) const private
Finds the tree index for a ModelPart pointer.
Parameters
part Part to locate.
Returns
Model index for the part, or invalid if not found.
Definition at line 1615 of file mainwindow.cpp.
References findIndexForPartRecursive().
Referenced by applyVrColorUpdate(), selectViewPart(), and setHoveredPart().
findIndexForPartRecursive()
QModelIndex MainWindow::findIndexForPartRecursive (const QModelIndex & parentIndex, ModelPart * part) const private
Recursive implementation of findIndexForPart().
Parameters
parentIndex Parent index to search below.
part Part to locate.
Returns
Model index for the part, or invalid if not found.
Definition at line 1620 of file mainwindow.cpp.
References findIndexForPartRecursive(), ModelPartList::index(), partList, and ModelPartList::rowCount().
Referenced by findIndexForPart(), and findIndexForPartRecursive().
findPartById()
ModelPart * MainWindow::findPartById (const QString & id) const private
Finds a part by its stable id.
Parameters
id UUID string assigned by ModelPart.
Returns
Part pointer, or nullptr if not found.
Definition at line 1636 of file mainwindow.cpp.
References findPartByIdRecursive().
Referenced by applyVrColorUpdate(), applyVrTransformUpdate(), and commitPendingVrTransforms().
findPartByIdRecursive()
ModelPart * MainWindow::findPartByIdRecursive (const QModelIndex & parentIndex, const QString & id) const private
Recursive implementation of findPartById().
Parameters
parentIndex Parent index to search below.
id UUID string assigned by ModelPart.
Returns
Part pointer, or nullptr if not found.
Definition at line 1641 of file mainwindow.cpp.
References findPartByIdRecursive(), ModelPart::id(), ModelPartList::index(), partList, and ModelPartList::rowCount().
Referenced by findPartById(), and findPartByIdRecursive().
fitCameraToScene()
void MainWindow::fitCameraToScene () private
Fits the desktop camera to the loaded scene.
Definition at line 1230 of file mainwindow.cpp.
References renderer, renderWindow, and ui.
Referenced by configureActions(), and rebuildScene().
getGroupMembers()
QList< ModelPart * > MainWindow::getGroupMembers (const QModelIndex & parentIndex, const QString & groupName) private
Finds all parts assigned to a group.
Parameters
parentIndex Tree index from which to start recursion.
groupName Group name to match.
Returns
List of matching parts.
Definition at line 2651 of file mainwindow.cpp.
References getGroupMembers(), ModelPart::getGroupName(), ModelPartList::index(), partList, and ModelPartList::rowCount().
Referenced by getGroupMembers(), on_itemScaleSlider_valueChanged(), and selectedTransformTargets().
handleButton
void MainWindow::handleButton () slot
Adds a new child item under the selected tree item.
Definition at line 1835 of file mainwindow.cpp.
References ModelPartList::appendChild(), ModelPart::data(), normalizedTreeIndex(), partList, statusUpdateMessage(), and ui.
Referenced by MainWindow().
handleSearchTextChanged
void MainWindow::handleSearchTextChanged (const QString & text) private slot
Filters the tree view by search text.
Parameters
text Search string typed by the user.
Definition at line 1316 of file mainwindow.cpp.
References applyTreeFilter().
Referenced by MainWindow().
handleTreeClicked
void MainWindow::handleTreeClicked () slot
Handles tree selection changes and synchronises the 3D selection state.
Definition at line 1854 of file mainwindow.cpp.
References ModelPart::data(), ModelPart::getScale(), normalizedTreeIndex(), selectionDetailsLabel, selectViewPart(), statusUpdateMessage(), ModelPart::summary(), and ui.
Referenced by MainWindow().
handleVtkClickEvent()
void MainWindow::handleVtkClickEvent () private
Handles a VTK left-click callback and selects the picked part.
Definition at line 1669 of file mainwindow.cpp.
References actorPartMap, propPicker, renderer, selectViewPart(), statusUpdateMessage(), and ui.
Referenced by setupRenderingPipeline().
handleVtkHoverEvent()
void MainWindow::handleVtkHoverEvent () private
Handles a VTK mouse-move callback and updates hover highlighting.
Definition at line 1657 of file mainwindow.cpp.
References actorPartMap, hoverPickIntervalMs, hoverPickTimer, propPicker, renderer, setHoveredPart(), and ui.
Referenced by setupRenderingPipeline().
importHdrFile()
void MainWindow::importHdrFile () private
Imports a user-selected HDR file into the environment selector.
Definition at line 1061 of file mainwindow.cpp.
References hdrComboBox, and statusUpdateMessage().
Referenced by setupProfessionalUi().
normalizedTreeIndex()
QModelIndex MainWindow::normalizedTreeIndex (const QModelIndex & index) const private
Converts any tree index to its column-0 equivalent.
Parameters
index Original index.
Returns
Column-0 index for the same row, or invalid if input is invalid.
Definition at line 1198 of file mainwindow.cpp.
Referenced by configureActions(), handleButton(), handleTreeClicked(), on_actionAdd_Item_triggered(), on_actionDelete_Item_triggered(), on_actionLock_to_New_Group_triggered(), on_actionOpen_File_triggered(), on_actionOpen_Folder_triggered(), and on_itemScaleSlider_valueChanged().
on_actionAdd_Item_triggered
void MainWindow::on_actionAdd_Item_triggered () slot
Adds an empty child item under the current selection.
Definition at line 2199 of file mainwindow.cpp.
References ModelPartList::appendChild(), normalizedTreeIndex(), partList, ModelPart::setColour(), ModelPart::setVisible(), statusUpdateMessage(), ui, and updateRender().
on_actionAdd_Level_triggered
void MainWindow::on_actionAdd_Level_triggered () slot
Adds an empty top-level tree item.
Definition at line 2182 of file mainwindow.cpp.
References ModelPartList::appendChild(), partList, ModelPart::setColour(), ModelPart::setVisible(), ui, and updateRender().
on_actionDelete_Item_triggered
void MainWindow::on_actionDelete_Item_triggered () slot
Deletes the selected tree item after confirmation.
Definition at line 2222 of file mainwindow.cpp.
References ModelPart::data(), hoveredPart, normalizedTreeIndex(), partList, ModelPartList::removePart(), selectedViewPart, selectionDetailsLabel, statusUpdateMessage(), syncTransformControls(), ui, undoStack, updateRender(), and updateSceneSummary().
on_actionLock_to_New_Group_triggered
void MainWindow::on_actionLock_to_New_Group_triggered () private slot
Locks selected parts into a new movement group.
Definition at line 2515 of file mainwindow.cpp.
References ModelPart::data(), ModelPart::isLockedInGroup(), normalizedTreeIndex(), ModelPart::setGroupName(), statusUpdateMessage(), and ui.
on_actionOpen_File_triggered
void MainWindow::on_actionOpen_File_triggered () slot
Opens one STL file and loads it into the selected or new tree item.
Definition at line 1870 of file mainwindow.cpp.
References ModelPartList::appendChild(), bulkLoading, centerModelAtOrigin(), loadProgressBar, ModelPart::loadSTL(), normalizedTreeIndex(), partList, rebuildScene(), selectionDetailsLabel, selectViewPart(), ModelPart::set(), statusUpdateMessage(), ModelPart::summary(), ui, and updateSceneSummary().
on_actionOpen_Folder_triggered
void MainWindow::on_actionOpen_Folder_triggered () slot
Opens a folder and loads all discovered STL files into the tree.
Definition at line 2372 of file mainwindow.cpp.
References ModelPartList::appendChild(), bulkLoading, centerModelAtOrigin(), loadProgressBar, ModelPart::loadSTL(), normalizedTreeIndex(), partList, rebuildScene(), ModelPartList::removePart(), statusUpdateMessage(), ui, and updateSceneSummary().
on_actionPause_VR_triggered
void MainWindow::on_actionPause_VR_triggered () private slot
Pauses or resumes VR animation.
Definition at line 2507 of file mainwindow.cpp.
References VRRenderThread::issueCommand(), VRRenderThread::PAUSE_RENDER, ui, and vrThread.
on_actionStart_VR_triggered
void MainWindow::on_actionStart_VR_triggered () private slot
Starts the VR render thread and transfers actor snapshots.
Definition at line 2255 of file mainwindow.cpp.
References VRRenderThread::actorColorChanged(), VRRenderThread::actorTransformChanged(), applyVrColorUpdate(), applyVrTransformUpdate(), collectActorsForVR(), collectModelBounds(), collectSceneStats(), hdrComboBox, hdrHeadingSpin, hdrTiltSpin, hdrTiltYSpin, VRRenderThread::issueCommand(), VRRenderThread::SET_SHOWCASE_SPIN, VRRenderThread::setEnvironmentOrientation(), VRRenderThread::setEnvironmentPath(), VRRenderThread::setSceneBounds(), VRRenderThread::setViewMode(), VRRenderThread::setViewTuning(), VRRenderThread::setViewYawDegrees(), showcaseSpinAction, statusUpdateMessage(), ui, vrDistanceSpin, vrHeightOffsetSpin, vrModelSizeSpin, vrThread, vrViewAngleCombo, and vrViewModeCombo.
on_actionStop_VR_triggered
void MainWindow::on_actionStop_VR_triggered () private slot
Stops the VR render thread.
Definition at line 2499 of file mainwindow.cpp.
References statusUpdateMessage(), stopVRThread(), and ui.
on_actionToggle_Filter_triggered
void MainWindow::on_actionToggle_Filter_triggered () private slot
Toggles whether hidden parts are removed from the renderer.
Definition at line 2334 of file mainwindow.cpp.
References statusUpdateMessage(), ui, updateRender(), and visibilityFilterOn.
on_actionUnlock_Item_triggered
void MainWindow::on_actionUnlock_Item_triggered () private slot
Removes selected parts from their movement group.
Definition at line 2622 of file mainwindow.cpp.
References cleanupEmptyGroups(), ModelPart::setGroupName(), ui, and updateRender().
Referenced by configureActions().
on_itemScaleSlider_valueChanged
void MainWindow::on_itemScaleSlider_valueChanged (int value) private slot
Updates selected part or group scale from the UI slider.
Parameters
value Slider value interpreted as percentage.
Definition at line 2476 of file mainwindow.cpp.
References getGroupMembers(), ModelPart::getGroupName(), normalizedTreeIndex(), renderWindow, ModelPart::setScale(), syncTransformControls(), and ui.
on_lightSlider_valueChanged
void MainWindow::on_lightSlider_valueChanged (int value) private slot
Updates the scene light intensity from the UI slider.
Parameters
value Slider value.
Definition at line 2359 of file mainwindow.cpp.
References renderer, and renderWindow.
on_zoomSlider_valueChanged
void MainWindow::on_zoomSlider_valueChanged (int value) private slot
Updates the desktop camera zoom from the UI slider.
Parameters
value Slider value interpreted as percentage.
Definition at line 2347 of file mainwindow.cpp.
References renderer, and renderWindow.
populateHdrOptions()
void MainWindow::populateHdrOptions () private
Populates the HDR combo box with built-in and remembered environments.
Definition at line 1022 of file mainwindow.cpp.
References hdrComboBox.
Referenced by setupRenderingPipeline().
rebuildScene()
void MainWindow::rebuildScene (bool resetCamera) private
Rebuilds all desktop scene props from the current model state.
Parameters
resetCamera True to refit the camera after rebuilding.
Definition at line 1204 of file mainwindow.cpp.
References actorPartMap, addPersistentSceneProps(), fitCameraToScene(), propPicker, renderer, renderWindow, and updateRenderFromTree().
Referenced by applyEnvironmentSelection(), configureActions(), on_actionOpen_File_triggered(), on_actionOpen_Folder_triggered(), and updateRender().
resetSelectedTransform
void MainWindow::resetSelectedTransform () private slot
Resets selected part transforms to identity.
Definition at line 1546 of file mainwindow.cpp.
References applyTransformFromControls(), positionSpin, rotationSpin, selectedViewPart, and transformScaleSpin.
Referenced by setupProfessionalUi().
resetVrView()
void MainWindow::resetVrView () private
Resets the active VR view using current UI tuning controls.
Definition at line 1793 of file mainwindow.cpp.
References collectModelBounds(), VRRenderThread::issueCommand(), VRRenderThread::RESET_VIEW, VRRenderThread::setSceneBounds(), VRRenderThread::setViewMode(), VRRenderThread::setViewTuning(), VRRenderThread::setViewYawDegrees(), statusUpdateMessage(), vrDistanceSpin, vrHeightOffsetSpin, vrModelSizeSpin, vrThread, vrViewAngleCombo, and vrViewModeCombo.
Referenced by setupProfessionalUi().
selectedTransformTargets()
QList< ModelPart * > MainWindow::selectedTransformTargets () const private
Gets the current transform targets, expanding groups when needed.
Returns
List of parts affected by transform controls.
Definition at line 1432 of file mainwindow.cpp.
References getGroupMembers(), ModelPart::getGroupName(), and selectedViewPart.
Referenced by applyTransformFromControls().
selectViewPart()
void MainWindow::selectViewPart (ModelPart * part) private
Selects a part from the desktop 3D view and synchronises the tree.
Parameters
part Selected part, or nullptr to clear selection.
Definition at line 1583 of file mainwindow.cpp.
References findIndexForPart(), partList, renderWindow, selectedViewPart, selectionDetailsLabel, ModelPart::setSelectedInView(), ModelPart::summary(), syncTransformControls(), and ui.
Referenced by handleTreeClicked(), handleVtkClickEvent(), and on_actionOpen_File_triggered().
setHoveredPart()
void MainWindow::setHoveredPart (ModelPart * part) private
Updates hover highlighting in the tree and 3D view.
Parameters
part Part under the cursor, or nullptr to clear hover.
Definition at line 1558 of file mainwindow.cpp.
References findIndexForPart(), hoveredPart, partList, renderWindow, selectionDetailsLabel, ModelPart::setHighlighted(), and ModelPart::summary().
Referenced by handleVtkHoverEvent().
setupProfessionalUi()
void MainWindow::setupProfessionalUi () private
Builds the professional dark UI around the generated widgets.
Definition at line 476 of file mainwindow.cpp.
References applyEnvironmentOrientation(), applyTransformButton, applyTransformFromControls(), applyTreeScale(), applyVrTuningToThread(), commitPendingVrTransforms(), hdrComboBox, hdrHeadingSpin, hdrTiltSpin, hdrTiltYSpin, importHdrButton, importHdrFile(), loadProgressBar, mainSplitter, positionSpin, resetSelectedTransform(), resetTransformButton, resetVrView(), resetVrViewButton, rotationSpin, sceneStatsLabel, searchEdit, selectionDetailsLabel, VRRenderThread::setViewMode(), VRRenderThread::setViewYawDegrees(), VRRenderThread::SITTING_VIEW, VRRenderThread::STANDING_VIEW, transformScaleSpin, treeScaleSlider, ui, vrDistanceSpin, vrHeightOffsetSpin, vrModelSizeSpin, vrThread, vrTransformCommitTimer, vrViewAngleCombo, and vrViewModeCombo.
Referenced by MainWindow().
setupRenderingPipeline()
void MainWindow::setupRenderingPipeline () private
Creates the desktop VTK renderer, render window, pickers, and callbacks.
Definition at line 900 of file mainwindow.cpp.
References addPersistentSceneProps(), applyEnvironmentOrientation(), applyEnvironmentSelection(), applyPerformanceMode(), createGridActor(), handleVtkClickEvent(), handleVtkHoverEvent(), hdrComboBox, hoverPickTimer, leftClickCallback, mouseMoveCallback, orientationMarker, performanceAction, populateHdrOptions(), propPicker, renderer, renderWindow, and ui.
Referenced by MainWindow().
statusUpdateMessage
void MainWindow::statusUpdateMessage (const QString & message, int timeout) signal
Requests a status-bar message.
Parameters
message Text to display.
timeout Duration in milliseconds; zero keeps the message until replaced.
Referenced by applyEnvironmentSelection(), applyVrColorUpdate(), configureActions(), handleButton(), handleTreeClicked(), handleVtkClickEvent(), importHdrFile(), MainWindow(), on_actionAdd_Item_triggered(), on_actionDelete_Item_triggered(), on_actionLock_to_New_Group_triggered(), on_actionOpen_File_triggered(), on_actionOpen_Folder_triggered(), on_actionStart_VR_triggered(), on_actionStop_VR_triggered(), on_actionToggle_Filter_triggered(), and resetVrView().
stopVRThread()
void MainWindow::stopVRThread () private
Safely stops and deletes the VR thread if it exists.
Definition at line 1814 of file mainwindow.cpp.
References commitPendingVrTransforms(), VRRenderThread::END_RENDER, VRRenderThread::issueCommand(), vrThread, and vrTransformCommitTimer.
Referenced by on_actionStop_VR_triggered(), and ~MainWindow().
syncTransformControls()
void MainWindow::syncTransformControls (ModelPart * part) private
Copies a part transform into the transform spin boxes.
Parameters
part Part whose transform should be displayed, or nullptr to clear state.
Definition at line 1448 of file mainwindow.cpp.
References applyTransformButton, ModelPart::getPosition(), ModelPart::getRotation(), ModelPart::getScale(), positionSpin, resetTransformButton, rotationSpin, and transformScaleSpin.
Referenced by applyTransformStates(), applyVrTransformUpdate(), configureActions(), MainWindow(), on_actionDelete_Item_triggered(), on_itemScaleSlider_valueChanged(), and selectViewPart().
translateModelParts()
void MainWindow::translateModelParts (const QModelIndex & parentIndex, double dx, double dy, double dz) private
Recursively translates model parts by a delta.
Parameters
parentIndex Parent index defining the subtree to translate.
dx X delta in model units.
dy Y delta in model units.
dz Z delta in model units.
Definition at line 1387 of file mainwindow.cpp.
References ModelPart::getPosition(), ModelPart::hasGeometry(), ModelPartList::index(), partList, ModelPartList::rowCount(), ModelPart::setPosition(), and translateModelParts().
Referenced by centerModelAtOrigin(), and translateModelParts().
updateRender
void MainWindow::updateRender () private slot
Rebuilds the desktop scene without resetting the camera.
Definition at line 2135 of file mainwindow.cpp.
References rebuildScene().
Referenced by cleanupEmptyGroups(), MainWindow(), on_actionAdd_Item_triggered(), on_actionAdd_Level_triggered(), on_actionDelete_Item_triggered(), on_actionToggle_Filter_triggered(), and on_actionUnlock_Item_triggered().
updateRenderFromTree
void MainWindow::updateRenderFromTree (const QModelIndex & index, QMap< QString, vtkSmartPointer< vtkAssembly > > & assemblies) private slot
Recursively adds visible actors from the tree into the VTK scene.
Parameters
index Current tree index being visited.
assemblies Map of group names to VTK assemblies under construction.
Definition at line 2139 of file mainwindow.cpp.
References actorPartMap, ModelPart::getActor(), ModelPart::getColourB(), ModelPart::getColourG(), ModelPart::getColourR(), ModelPart::getGroupName(), ModelPartList::index(), partList, propPicker, renderer, ModelPartList::rowCount(), updateRenderFromTree(), visibilityFilterOn, and ModelPart::visible().
Referenced by rebuildScene(), and updateRenderFromTree().
updateSceneSummary()
void MainWindow::updateSceneSummary () private
Recalculates scene statistics and updates the status label.
Definition at line 1418 of file mainwindow.cpp.
References collectSceneStats(), and sceneStatsLabel.
Referenced by configureActions(), MainWindow(), on_actionDelete_Item_triggered(), on_actionOpen_File_triggered(), and on_actionOpen_Folder_triggered().
Member Data Documentation
actorPartMap
QHash<vtkActor*, ModelPart*> MainWindow::actorPartMap private
Desktop actor to ModelPart lookup table.
Definition at line 270 of file mainwindow.h.
Referenced by handleVtkClickEvent(), handleVtkHoverEvent(), rebuildScene(), and updateRenderFromTree().
applyTransformButton
QPushButton* MainWindow::applyTransformButton = nullptr private
Button that applies transform spin-box values.
Definition at line 239 of file mainwindow.h.
Referenced by setupProfessionalUi(), and syncTransformControls().
bulkLoading
bool MainWindow::bulkLoading = false private
True while loading many STL files to suppress expensive updates.
Definition at line 249 of file mainwindow.h.
Referenced by MainWindow(), on_actionOpen_File_triggered(), and on_actionOpen_Folder_triggered().
environmentActor
vtkSmartPointer<vtkActor> MainWindow::environmentActor private
Legacy environment actor placeholder.
Definition at line 261 of file mainwindow.h.
Referenced by addPersistentSceneProps(), and applyEnvironmentSelection().
environmentBaseImage
vtkSmartPointer<vtkImageData> MainWindow::environmentBaseImage private
Tonemapped HDR image before orientation.
Definition at line 263 of file mainwindow.h.
Referenced by applyEnvironmentOrientation(), and applyEnvironmentSelection().
environmentImage
vtkSmartPointer<vtkImageData> MainWindow::environmentImage private
Oriented HDR image currently displayed.
Definition at line 264 of file mainwindow.h.
Referenced by applyEnvironmentOrientation(), and applyEnvironmentSelection().
environmentTexture
vtkSmartPointer<vtkTexture> MainWindow::environmentTexture private
Desktop HDR environment texture.
Definition at line 262 of file mainwindow.h.
Referenced by applyEnvironmentOrientation(), and applyEnvironmentSelection().
gridAction
QAction* MainWindow::gridAction = nullptr private
Toolbar action that toggles the floor grid.
Definition at line 244 of file mainwindow.h.
Referenced by addPersistentSceneProps(), and configureActions().
gridActor
vtkSmartPointer<vtkActor> MainWindow::gridActor private
Floor grid actor.
Definition at line 260 of file mainwindow.h.
Referenced by addPersistentSceneProps(), configureActions(), and createGridActor().
groupAssemblies
QMap<QString, vtkSmartPointer<vtkAssembly> > MainWindow::groupAssemblies private
Group-name to VTK assembly map.
Definition at line 269 of file mainwindow.h.
hdrComboBox
QComboBox* MainWindow::hdrComboBox = nullptr private
Environment selector for built-in and imported HDR files.
Definition at line 221 of file mainwindow.h.
Referenced by applyEnvironmentSelection(), importHdrFile(), on_actionStart_VR_triggered(), populateHdrOptions(), setupProfessionalUi(), and setupRenderingPipeline().
hdrHeadingSpin
QDoubleSpinBox* MainWindow::hdrHeadingSpin = nullptr private
HDR heading control in degrees.
Definition at line 227 of file mainwindow.h.
Referenced by applyEnvironmentOrientation(), on_actionStart_VR_triggered(), and setupProfessionalUi().
hdrTiltSpin
QDoubleSpinBox* MainWindow::hdrTiltSpin = nullptr private
HDR X tilt control in degrees.
Definition at line 225 of file mainwindow.h.
Referenced by applyEnvironmentOrientation(), on_actionStart_VR_triggered(), and setupProfessionalUi().
hdrTiltYSpin
QDoubleSpinBox* MainWindow::hdrTiltYSpin = nullptr private
HDR Y tilt control in degrees.
Definition at line 226 of file mainwindow.h.
Referenced by applyEnvironmentOrientation(), on_actionStart_VR_triggered(), and setupProfessionalUi().
hoveredPart
ModelPart* MainWindow::hoveredPart = nullptr private
Part currently highlighted by hover.
Definition at line 271 of file mainwindow.h.
Referenced by configureActions(), on_actionDelete_Item_triggered(), and setHoveredPart().
hoverPickIntervalMs
int MainWindow::hoverPickIntervalMs = 55 private
Minimum delay between hover-picking operations.
Definition at line 250 of file mainwindow.h.
Referenced by applyPerformanceMode(), and handleVtkHoverEvent().
hoverPickTimer
QElapsedTimer MainWindow::hoverPickTimer private
Timer used to throttle desktop hover picking.
Definition at line 251 of file mainwindow.h.
Referenced by handleVtkHoverEvent(), and setupRenderingPipeline().
importHdrButton
QPushButton* MainWindow::importHdrButton = nullptr private
Button that imports a custom HDR file.
Definition at line 222 of file mainwindow.h.
Referenced by setupProfessionalUi().
leftClickCallback
vtkSmartPointer<vtkCallbackCommand> MainWindow::leftClickCallback private
VTK callback for click selection.
Definition at line 267 of file mainwindow.h.
Referenced by setupRenderingPipeline().
loadProgressBar
QProgressBar* MainWindow::loadProgressBar = nullptr private
Progress indicator for bulk STL loading.
Definition at line 233 of file mainwindow.h.
Referenced by on_actionOpen_File_triggered(), on_actionOpen_Folder_triggered(), and setupProfessionalUi().
mainSplitter
QSplitter* MainWindow::mainSplitter = nullptr private
Main left/view/right splitter that makes panels resizable.
Definition at line 242 of file mainwindow.h.
Referenced by configureActions(), and setupProfessionalUi().
mouseMoveCallback
vtkSmartPointer<vtkCallbackCommand> MainWindow::mouseMoveCallback private
VTK callback for hover events.
Definition at line 266 of file mainwindow.h.
Referenced by setupRenderingPipeline().
mySkybox
vtkSmartPointer<vtkSkybox> MainWindow::mySkybox private
Desktop skybox actor for HDR environments.
Definition at line 258 of file mainwindow.h.
Referenced by addPersistentSceneProps(), applyEnvironmentOrientation(), and applyEnvironmentSelection().
orientationMarker
vtkSmartPointer<vtkOrientationMarkerWidget> MainWindow::orientationMarker private
Small orientation axes widget.
Definition at line 259 of file mainwindow.h.
Referenced by setupRenderingPipeline().
partList
ModelPartList* MainWindow::partList private
Qt model containing all loaded ModelPart items.
Definition at line 219 of file mainwindow.h.
Referenced by applyTreeFilter(), applyVrColorUpdate(), collectActorsForVR(), collectModelBounds(), collectSceneStats(), configureActions(), findIndexForPartRecursive(), findPartByIdRecursive(), getGroupMembers(), handleButton(), MainWindow(), on_actionAdd_Item_triggered(), on_actionAdd_Level_triggered(), on_actionDelete_Item_triggered(), on_actionOpen_File_triggered(), on_actionOpen_Folder_triggered(), selectViewPart(), setHoveredPart(), translateModelParts(), and updateRenderFromTree().
pendingVrTransformLatestStates
QHash<QString, ModelPart::TransformState> MainWindow::pendingVrTransformLatestStates private
Latest transforms received from VR before commit.
Definition at line 254 of file mainwindow.h.
Referenced by applyVrTransformUpdate(), and commitPendingVrTransforms().
pendingVrTransformStartStates
QHash<QString, ModelPart::TransformState> MainWindow::pendingVrTransformStartStates private
Original transforms for pending VR undo commands.
Definition at line 253 of file mainwindow.h.
Referenced by applyVrTransformUpdate(), and commitPendingVrTransforms().
performanceAction
QAction* MainWindow::performanceAction = nullptr private
Toolbar action that toggles high-performance rendering mode.
Definition at line 245 of file mainwindow.h.
Referenced by configureActions(), and setupRenderingPipeline().
positionSpin
QDoubleSpinBox* MainWindow::positionSpin[3] = { nullptr, nullptr, nullptr } private
XYZ position controls.
Definition at line 236 of file mainwindow.h.
Referenced by applyTransformFromControls(), resetSelectedTransform(), setupProfessionalUi(), and syncTransformControls().
propPicker
vtkSmartPointer<vtkPropPicker> MainWindow::propPicker private
Picker used for hover and click selection.
Definition at line 265 of file mainwindow.h.
Referenced by handleVtkClickEvent(), handleVtkHoverEvent(), rebuildScene(), setupRenderingPipeline(), and updateRenderFromTree().
renderer
vtkSmartPointer<vtkRenderer> MainWindow::renderer private
Desktop VTK renderer.
Definition at line 256 of file mainwindow.h.
Referenced by addPersistentSceneProps(), applyEnvironmentOrientation(), applyEnvironmentSelection(), applyTransformStates(), applyVrTransformUpdate(), fitCameraToScene(), handleVtkClickEvent(), handleVtkHoverEvent(), on_lightSlider_valueChanged(), on_zoomSlider_valueChanged(), rebuildScene(), setupRenderingPipeline(), and updateRenderFromTree().
renderWindow
vtkSmartPointer<vtkGenericOpenGLRenderWindow> MainWindow::renderWindow private
Qt-compatible OpenGL render window.
Definition at line 257 of file mainwindow.h.
Referenced by applyEnvironmentOrientation(), applyPerformanceMode(), applyTransformStates(), applyVrColorUpdate(), applyVrTransformUpdate(), configureActions(), fitCameraToScene(), on_itemScaleSlider_valueChanged(), on_lightSlider_valueChanged(), on_zoomSlider_valueChanged(), rebuildScene(), selectViewPart(), setHoveredPart(), and setupRenderingPipeline().
resetTransformButton
QPushButton* MainWindow::resetTransformButton = nullptr private
Button that resets selected transform values.
Definition at line 240 of file mainwindow.h.
Referenced by setupProfessionalUi(), and syncTransformControls().
resetVrViewButton
QPushButton* MainWindow::resetVrViewButton = nullptr private
Button that resets the headset view pose.
Definition at line 241 of file mainwindow.h.
Referenced by setupProfessionalUi().
rotationSpin
QDoubleSpinBox* MainWindow::rotationSpin[3] = { nullptr, nullptr, nullptr } private
XYZ rotation controls.
Definition at line 237 of file mainwindow.h.
Referenced by applyTransformFromControls(), resetSelectedTransform(), setupProfessionalUi(), and syncTransformControls().
sceneStatsLabel
QLabel* MainWindow::sceneStatsLabel = nullptr private
Status bar label showing scene totals.
Definition at line 231 of file mainwindow.h.
Referenced by setupProfessionalUi(), and updateSceneSummary().
searchEdit
QLineEdit* MainWindow::searchEdit = nullptr private
Search box used to filter the tree view.
Definition at line 220 of file mainwindow.h.
Referenced by MainWindow(), and setupProfessionalUi().
selectedViewPart
ModelPart* MainWindow::selectedViewPart = nullptr private
Part currently selected in the 3D view.
Definition at line 272 of file mainwindow.h.
Referenced by applyTransformFromControls(), applyTransformStates(), applyVrTransformUpdate(), configureActions(), on_actionDelete_Item_triggered(), resetSelectedTransform(), selectedTransformTargets(), and selectViewPart().
selectionDetailsLabel
QLabel* MainWindow::selectionDetailsLabel = nullptr private
Status bar label showing selected part details.
Definition at line 232 of file mainwindow.h.
Referenced by configureActions(), handleTreeClicked(), on_actionDelete_Item_triggered(), on_actionOpen_File_triggered(), selectViewPart(), setHoveredPart(), and setupProfessionalUi().
showcaseSpinAction
QAction* MainWindow::showcaseSpinAction = nullptr private
Toolbar action that toggles automatic showcase rotation.
Definition at line 246 of file mainwindow.h.
Referenced by configureActions(), and on_actionStart_VR_triggered().
transformScaleSpin
QDoubleSpinBox* MainWindow::transformScaleSpin = nullptr private
Uniform transform scale control.
Definition at line 238 of file mainwindow.h.
Referenced by applyTransformFromControls(), resetSelectedTransform(), setupProfessionalUi(), and syncTransformControls().
treeScaleSlider
QSlider* MainWindow::treeScaleSlider = nullptr private
UI control that scales the tree view font and row size.
Definition at line 235 of file mainwindow.h.
Referenced by setupProfessionalUi().
ui
Ui::MainWindow* MainWindow::ui private
Generated widget tree from mainwindow.ui.
Definition at line 218 of file mainwindow.h.
Referenced by applyPerformanceMode(), applyTreeFilter(), applyTreeScale(), cleanupEmptyGroups(), configureActions(), fitCameraToScene(), handleButton(), handleTreeClicked(), handleVtkClickEvent(), handleVtkHoverEvent(), MainWindow(), on_actionAdd_Item_triggered(), on_actionAdd_Level_triggered(), on_actionDelete_Item_triggered(), on_actionLock_to_New_Group_triggered(), on_actionOpen_File_triggered(), on_actionOpen_Folder_triggered(), on_actionPause_VR_triggered(), on_actionStart_VR_triggered(), on_actionStop_VR_triggered(), on_actionToggle_Filter_triggered(), on_actionUnlock_Item_triggered(), on_itemScaleSlider_valueChanged(), selectViewPart(), setupProfessionalUi(), setupRenderingPipeline(), and ~MainWindow().
undoStack
QUndoStack* MainWindow::undoStack = nullptr private
Undo/redo stack for transforms and VR moves.
Definition at line 243 of file mainwindow.h.
Referenced by applyTransformFromControls(), commitPendingVrTransforms(), configureActions(), MainWindow(), and on_actionDelete_Item_triggered().
visibilityFilterOn
bool MainWindow::visibilityFilterOn = false private
True when hidden parts are excluded from the renderer.
Definition at line 248 of file mainwindow.h.
Referenced by configureActions(), on_actionToggle_Filter_triggered(), and updateRenderFromTree().
vrDistanceSpin
QDoubleSpinBox* MainWindow::vrDistanceSpin = nullptr private
VR reset-view standoff distance.
Definition at line 229 of file mainwindow.h.
Referenced by applyVrTuningToThread(), on_actionStart_VR_triggered(), resetVrView(), and setupProfessionalUi().
vrHeightOffsetSpin
QDoubleSpinBox* MainWindow::vrHeightOffsetSpin = nullptr private
VR headset height fine-tuning offset.
Definition at line 230 of file mainwindow.h.
Referenced by applyVrTuningToThread(), on_actionStart_VR_triggered(), resetVrView(), and setupProfessionalUi().
vrModelSizeSpin
QDoubleSpinBox* MainWindow::vrModelSizeSpin = nullptr private
Target model size in VR metres.
Definition at line 228 of file mainwindow.h.
Referenced by applyVrTuningToThread(), on_actionStart_VR_triggered(), resetVrView(), and setupProfessionalUi().
vrThread
VRRenderThread* MainWindow::vrThread = nullptr private
Active VR worker thread, or nullptr when VR is stopped.
Definition at line 511 of file mainwindow.h.
Referenced by applyEnvironmentOrientation(), applyEnvironmentSelection(), applyVrTuningToThread(), collectActorsForVR(), configureActions(), on_actionPause_VR_triggered(), on_actionStart_VR_triggered(), resetVrView(), setupProfessionalUi(), and stopVRThread().
vrTransformCommitTimer
QTimer* MainWindow::vrTransformCommitTimer = nullptr private
Debounces VR move updates into one undo command.
Definition at line 234 of file mainwindow.h.
Referenced by applyVrTransformUpdate(), setupProfessionalUi(), and stopVRThread().
vrTransformRenderTimer
QElapsedTimer MainWindow::vrTransformRenderTimer private
Timer used to throttle desktop redraws from VR movement.
Definition at line 252 of file mainwindow.h.
Referenced by applyVrTransformUpdate().
vrViewAngleCombo
QComboBox* MainWindow::vrViewAngleCombo = nullptr private
Preset camera yaw selector for VR reset.
Definition at line 224 of file mainwindow.h.
Referenced by on_actionStart_VR_triggered(), resetVrView(), and setupProfessionalUi().
vrViewModeCombo
QComboBox* MainWindow::vrViewModeCombo = nullptr private
Standing/sitting VR mode selector.
Definition at line 223 of file mainwindow.h.
Referenced by on_actionStart_VR_triggered(), resetVrView(), and setupProfessionalUi().
The documentation for this class was generated from the following files:
mainwindow.h
mainwindow.cpp