VR Model Viewer: Dialog Class Reference
Dialog Class Reference
Modal Qt dialog for editing a part's display options.
#include <dialog.h>
Signals
void previewChanged (const QString &name, bool visible, int r, int g, int b, bool shrinkEnabled, bool clipEnabled, int filterOrder, bool glowEnabled, int glowR, int glowG, int glowB)
Emitted when lightweight preview properties change.
Public Member Functions
Dialog (QWidget *parent=nullptr)
Creates the part options dialog.
~Dialog ()
Destroys the dialog and releases the generated UI object.
void setName (const QString &name)
Sets the editable part name field.
void setPartVisibility (bool v)
Sets the visible checkbox state.
void setRGB (int r, int g, int b)
Sets the selected base colour.
QString getName () const
Reads the current part name from the dialog.
bool getVisible () const
Reads the visible checkbox state.
void getRGB (int &r, int &g, int &b) const
Reads the selected base colour.
void setShrinkEnabled (bool enabled)
Sets whether the shrink filter checkbox is enabled.
void setClipEnabled (bool enabled)
Sets whether the clip filter checkbox is enabled.
void setFilterOrder (int order)
Sets the selected filter order.
void setGlowEnabled (bool enabled)
Sets whether glow highlighting is enabled.
void setGlowRGB (int r, int g, int b)
Sets the glow highlight colour.
bool getShrinkEnabled () const
Reads the shrink filter checkbox.
bool getClipEnabled () const
Reads the clip filter checkbox.
int getFilterOrder () const
Reads the chosen filter order.
bool getGlowEnabled () const
Reads the glow checkbox state.
void getGlowRGB (int &r, int &g, int &b) const
Reads the selected glow highlight colour.
Private Slots
void on_pushButton_clicked ()
Opens the colour picker for the base part colour.
void onGlowColorClicked ()
Opens the colour picker for the glow colour.
Private Member Functions
void updateColorButton (QPushButton *button, const QColor &color)
Updates a colour button's swatch and readable foreground colour.
void emitPreviewChanged ()
Emits previewChanged with the dialog's current lightweight state.
Private Attributes
Ui::Dialog * ui
Generated widget tree from dialog.ui.
QColor selectedColor
Currently selected base part colour.
QColor selectedGlowColor = QColor(0, 180, 255)
Currently selected glow highlight colour.
QCheckBox * glowCheckBox = nullptr
Runtime-created checkbox for glow enable state.
QPushButton * glowColorButton = nullptr
Runtime-created button used to choose glow colour.
Detailed Description
Modal Qt dialog for editing a part's display options.
Dialog owns the widgets created from dialog.ui and adds a small set of custom controls for glow highlighting. Getter and setter methods are used by MainWindow to initialise the dialog from the selected part and read the final accepted state.
Definition at line 32 of file dialog.h.
Constructor & Destructor Documentation
Dialog()
Dialog::Dialog (QWidget * parent = nullptr) explicit
Creates the part options dialog.
Parameters
parent Optional parent widget used for Qt ownership and modality.
Definition at line 17 of file dialog.cpp.
References emitPreviewChanged(), glowCheckBox, glowColorButton, onGlowColorClicked(), and ui.
~Dialog()
Dialog::~Dialog ()
Destroys the dialog and releases the generated UI object.
Definition at line 47 of file dialog.cpp.
References ui.
Member Function Documentation
emitPreviewChanged()
void Dialog::emitPreviewChanged () private
Emits previewChanged with the dialog's current lightweight state.
Definition at line 170 of file dialog.cpp.
References getClipEnabled(), getFilterOrder(), getGlowEnabled(), getGlowRGB(), getName(), getRGB(), getShrinkEnabled(), getVisible(), and previewChanged().
Referenced by Dialog(), on_pushButton_clicked(), and onGlowColorClicked().
getClipEnabled()
bool Dialog::getClipEnabled () const
Reads the clip filter checkbox.
Returns
True if the clip filter should be applied.
Definition at line 124 of file dialog.cpp.
References ui.
Referenced by emitPreviewChanged().
getFilterOrder()
int Dialog::getFilterOrder () const
Reads the chosen filter order.
Returns
Combo-box index for filter ordering.
Definition at line 129 of file dialog.cpp.
References ui.
Referenced by emitPreviewChanged().
getGlowEnabled()
bool Dialog::getGlowEnabled () const
Reads the glow checkbox state.
Returns
True if glow highlighting should be applied.
Definition at line 149 of file dialog.cpp.
References glowCheckBox.
Referenced by emitPreviewChanged().
getGlowRGB()
void Dialog::getGlowRGB (int & r, int & g, int & b) const
Reads the selected glow highlight colour.
Parameters
r Output red channel in the range 0-255.
g Output green channel in the range 0-255.
b Output blue channel in the range 0-255.
Definition at line 154 of file dialog.cpp.
References selectedGlowColor.
Referenced by emitPreviewChanged().
getName()
QString Dialog::getName () const
Reads the current part name from the dialog.
Returns
Name currently typed by the user.
Definition at line 67 of file dialog.cpp.
References ui.
Referenced by emitPreviewChanged().
getRGB()
void Dialog::getRGB (int & r, int & g, int & b) const
Reads the selected base colour.
Parameters
r Output red channel in the range 0-255.
g Output green channel in the range 0-255.
b Output blue channel in the range 0-255.
Definition at line 75 of file dialog.cpp.
References selectedColor.
Referenced by emitPreviewChanged().
getShrinkEnabled()
bool Dialog::getShrinkEnabled () const
Reads the shrink filter checkbox.
Returns
True if the shrink filter should be applied.
Definition at line 119 of file dialog.cpp.
References ui.
Referenced by emitPreviewChanged().
getVisible()
bool Dialog::getVisible () const
Reads the visible checkbox state.
Returns
True when the part should be visible.
Definition at line 71 of file dialog.cpp.
References ui.
Referenced by emitPreviewChanged().
on_pushButton_clicked
void Dialog::on_pushButton_clicked () private slot
Opens the colour picker for the base part colour.
Definition at line 82 of file dialog.cpp.
References emitPreviewChanged(), selectedColor, ui, and updateColorButton().
onGlowColorClicked
void Dialog::onGlowColorClicked () private slot
Opens the colour picker for the glow colour.
Definition at line 94 of file dialog.cpp.
References emitPreviewChanged(), glowColorButton, selectedGlowColor, and updateColorButton().
Referenced by Dialog().
previewChanged
void Dialog::previewChanged (const QString & name, bool visible, int r, int g, int b, bool shrinkEnabled, bool clipEnabled, int filterOrder, bool glowEnabled, int glowR, int glowG, int glowB) signal
Emitted when lightweight preview properties change.
Parameters
name Current part name.
visible Current visibility state.
r Base colour red channel.
g Base colour green channel.
b Base colour blue channel.
shrinkEnabled Current shrink filter state.
clipEnabled Current clip filter state.
filterOrder Current filter order index.
glowEnabled Current glow state.
glowR Glow colour red channel.
glowG Glow colour green channel.
glowB Glow colour blue channel.
Referenced by emitPreviewChanged().
setClipEnabled()
void Dialog::setClipEnabled (bool enabled)
Sets whether the clip filter checkbox is enabled.
Parameters
enabled True to request the clip filter.
Definition at line 109 of file dialog.cpp.
References ui.
setFilterOrder()
void Dialog::setFilterOrder (int order)
Sets the selected filter order.
Parameters
order Combo-box index, where 0 is shrink-then-clip and 1 is clip-then-shrink.
Definition at line 114 of file dialog.cpp.
References ui.
setGlowEnabled()
void Dialog::setGlowEnabled (bool enabled)
Sets whether glow highlighting is enabled.
Parameters
enabled True to enable glow highlighting.
Definition at line 134 of file dialog.cpp.
References glowCheckBox.
setGlowRGB()
void Dialog::setGlowRGB (int r, int g, int b)
Sets the glow highlight colour.
Parameters
r Red channel in the range 0-255.
g Green channel in the range 0-255.
b Blue channel in the range 0-255.
Definition at line 141 of file dialog.cpp.
References glowColorButton, selectedGlowColor, and updateColorButton().
setName()
void Dialog::setName (const QString & name)
Sets the editable part name field.
Parameters
name Name to show in the dialog.
Definition at line 53 of file dialog.cpp.
References ui.
setPartVisibility()
void Dialog::setPartVisibility (bool v)
Sets the visible checkbox state.
Parameters
v True if the part should be visible.
Definition at line 57 of file dialog.cpp.
References ui.
setRGB()
void Dialog::setRGB (int r, int g, int b)
Sets the selected base colour.
Parameters
r Red channel in the range 0-255.
g Green channel in the range 0-255.
b Blue channel in the range 0-255.
Definition at line 61 of file dialog.cpp.
References selectedColor, ui, and updateColorButton().
setShrinkEnabled()
void Dialog::setShrinkEnabled (bool enabled)
Sets whether the shrink filter checkbox is enabled.
Parameters
enabled True to request the shrink filter.
Definition at line 104 of file dialog.cpp.
References ui.
updateColorButton()
void Dialog::updateColorButton (QPushButton * button, const QColor & color) private
Updates a colour button's swatch and readable foreground colour.
Parameters
button Button whose stylesheet should be updated.
color Colour represented by the button.
Definition at line 161 of file dialog.cpp.
Referenced by on_pushButton_clicked(), onGlowColorClicked(), setGlowRGB(), and setRGB().
Member Data Documentation
glowCheckBox
QCheckBox* Dialog::glowCheckBox = nullptr private
Runtime-created checkbox for glow enable state.
Definition at line 188 of file dialog.h.
Referenced by Dialog(), getGlowEnabled(), and setGlowEnabled().
glowColorButton
QPushButton* Dialog::glowColorButton = nullptr private
Runtime-created button used to choose glow colour.
Definition at line 189 of file dialog.h.
Referenced by Dialog(), onGlowColorClicked(), and setGlowRGB().
selectedColor
QColor Dialog::selectedColor private
Currently selected base part colour.
Definition at line 186 of file dialog.h.
Referenced by getRGB(), on_pushButton_clicked(), and setRGB().
selectedGlowColor
QColor Dialog::selectedGlowColor = QColor(0, 180, 255) private
Currently selected glow highlight colour.
Definition at line 187 of file dialog.h.
Referenced by getGlowRGB(), onGlowColorClicked(), and setGlowRGB().
ui
Ui::Dialog* Dialog::ui private
Generated widget tree from dialog.ui.
Definition at line 185 of file dialog.h.
Referenced by Dialog(), getClipEnabled(), getFilterOrder(), getName(), getShrinkEnabled(), getVisible(), on_pushButton_clicked(), setClipEnabled(), setFilterOrder(), setName(), setPartVisibility(), setRGB(), setShrinkEnabled(), and ~Dialog().
The documentation for this class was generated from the following files:
dialog.h
dialog.cpp