VR Model Viewer: ModelPartList Class Reference
ModelPartList Class Reference
QAbstractItemModel implementation backed by a ModelPart tree.
#include <ModelPartList.h>
Public Member Functions
ModelPartList (const QString &data, QObject *parent=NULL)
Constructs the model and creates the invisible root item.
~ModelPartList ()
Destroys the root item and therefore all child ModelPart objects.
int columnCount (const QModelIndex &parent) const
Reports how many columns the tree model exposes.
QVariant data (const QModelIndex &index, int role) const
Returns data requested by Qt views and delegates.
bool setData (const QModelIndex &index, const QVariant &value, int role) override
Applies edited names or check-box visibility changes.
Qt::ItemFlags flags (const QModelIndex &index) const
Reports item capabilities such as editing and checkability.
QVariant headerData (int section, Qt::Orientation orientation, int role) const
Returns header text for the tree columns.
QModelIndex index (int row, int column, const QModelIndex &parent) const
Creates a QModelIndex for a child item.
QModelIndex parent (const QModelIndex &index) const
Gets the parent index of a model item.
int rowCount (const QModelIndex &parent) const
Counts rows below a parent item.
ModelPart * getRootItem ()
Gets the invisible root ModelPart.
QModelIndex appendChild (const QModelIndex &parent, const QList< QVariant > &data)
Appends a new child item under a parent.
bool removePart (const QModelIndex &index)
Removes and deletes a part from the model.
Private Attributes
ModelPart * rootItem
Invisible root node that owns the entire ModelPart tree.
Detailed Description
QAbstractItemModel implementation backed by a ModelPart tree.
The model provides two columns: the part name and its visibility state. It also exposes editing, check-box visibility toggles, hover/selection colours, and helper methods for inserting and removing tree items.
Definition at line 31 of file ModelPartList.h.
Constructor & Destructor Documentation
ModelPartList()
ModelPartList::ModelPartList (const QString & data, QObject * parent = NULL)
Constructs the model and creates the invisible root item.
Parameters
data Unused legacy parameter retained for compatibility.
parent Optional QObject parent for Qt ownership.
Definition at line 14 of file ModelPartList.cpp.
References rootItem.
~ModelPartList()
ModelPartList::~ModelPartList ()
Destroys the root item and therefore all child ModelPart objects.
Definition at line 19 of file ModelPartList.cpp.
References rootItem.
Member Function Documentation
appendChild()
QModelIndex ModelPartList::appendChild (const QModelIndex & parent, const QList< QVariant > & data)
Appends a new child item under a parent.
Parameters
parent Parent index; invalid creates a top-level item.
data Column data for the new ModelPart.
Returns
Model index for the newly inserted child.
Definition at line 162 of file ModelPartList.cpp.
References ModelPart::appendChild(), ModelPart::childCount(), data(), parent(), and rootItem.
Referenced by MainWindow::handleButton(), MainWindow::on_actionAdd_Item_triggered(), MainWindow::on_actionAdd_Level_triggered(), MainWindow::on_actionOpen_File_triggered(), and MainWindow::on_actionOpen_Folder_triggered().
columnCount()
int ModelPartList::columnCount (const QModelIndex & parent) const
Reports how many columns the tree model exposes.
Parameters
parent Parent index requested by Qt; unused because all rows share the same columns.
Returns
Number of columns.
Definition at line 23 of file ModelPartList.cpp.
References ModelPart::columnCount(), parent(), and rootItem.
data()
QVariant ModelPartList::data (const QModelIndex & index, int role) const
Returns data requested by Qt views and delegates.
Parameters
index Model index identifying the row and column.
role Qt item data role, such as display, edit, tooltip, or background.
Returns
Data for the requested role, or an invalid QVariant when unavailable.
Definition at line 28 of file ModelPartList.cpp.
References ModelPart::data(), ModelPart::getGlowB(), ModelPart::getGlowG(), ModelPart::getGlowR(), ModelPart::glowEnabled(), ModelPart::highlighted(), index(), ModelPart::selectedInView(), ModelPart::summary(), and ModelPart::visible().
Referenced by appendChild().
flags()
Qt::ItemFlags ModelPartList::flags (const QModelIndex & index) const
Reports item capabilities such as editing and checkability.
Parameters
index Model index being queried.
Returns
Qt item flags for the index.
Definition at line 89 of file ModelPartList.cpp.
References index().
getRootItem()
ModelPart * ModelPartList::getRootItem ()
Gets the invisible root ModelPart.
Returns
Root item pointer owned by this model.
Definition at line 158 of file ModelPartList.cpp.
References rootItem.
headerData()
QVariant ModelPartList::headerData (int section, Qt::Orientation orientation, int role) const
Returns header text for the tree columns.
Parameters
section Header section index.
orientation Header orientation.
role Requested Qt role.
Returns
Header label for display role, otherwise an invalid QVariant.
Definition at line 103 of file ModelPartList.cpp.
References ModelPart::data(), and rootItem.
index()
QModelIndex ModelPartList::index (int row, int column, const QModelIndex & parent) const
Creates a QModelIndex for a child item.
Parameters
row Child row under parent.
column Column requested by Qt.
parent Parent model index; invalid means the root item.
Returns
Valid index for the child, or an invalid QModelIndex if out of range.
Definition at line 110 of file ModelPartList.cpp.
References ModelPart::child(), parent(), and rootItem.
Referenced by MainWindow::applyTreeFilter(), MainWindow::collectActorsForVR(), MainWindow::collectModelBounds(), MainWindow::collectSceneStats(), MainWindow::configureActions(), data(), MainWindow::findIndexForPartRecursive(), MainWindow::findPartByIdRecursive(), flags(), MainWindow::getGroupMembers(), parent(), removePart(), setData(), MainWindow::translateModelParts(), and MainWindow::updateRenderFromTree().
parent()
QModelIndex ModelPartList::parent (const QModelIndex & index) const
Gets the parent index of a model item.
Parameters
index Child index whose parent is requested.
Returns
Parent index, or invalid QModelIndex for top-level items.
Definition at line 132 of file ModelPartList.cpp.
References index(), ModelPart::parentItem(), rootItem, and ModelPart::row().
Referenced by appendChild(), columnCount(), index(), and rowCount().
removePart()
bool ModelPartList::removePart (const QModelIndex & index)
Removes and deletes a part from the model.
Parameters
index Index of the part to remove; any column is normalised to column 0.
Returns
True when a valid item was removed.
Definition at line 192 of file ModelPartList.cpp.
References index(), ModelPart::parentItem(), ModelPart::removeChild(), and ModelPart::row().
Referenced by MainWindow::configureActions(), MainWindow::on_actionDelete_Item_triggered(), and MainWindow::on_actionOpen_Folder_triggered().
rowCount()
int ModelPartList::rowCount (const QModelIndex & parent) const
Counts rows below a parent item.
Parameters
parent Parent model index; invalid means the root item.
Returns
Number of child rows.
Definition at line 145 of file ModelPartList.cpp.
References ModelPart::childCount(), parent(), and rootItem.
Referenced by MainWindow::applyTreeFilter(), MainWindow::collectActorsForVR(), MainWindow::collectModelBounds(), MainWindow::collectSceneStats(), MainWindow::configureActions(), MainWindow::findIndexForPartRecursive(), MainWindow::findPartByIdRecursive(), MainWindow::getGroupMembers(), MainWindow::translateModelParts(), and MainWindow::updateRenderFromTree().
setData()
bool ModelPartList::setData (const QModelIndex & index, const QVariant & value, int role) override
Applies edited names or check-box visibility changes.
Parameters
index Model index being edited.
value New value supplied by the view/delegate.
role Role being written, usually Qt::EditRole or Qt::CheckStateRole.
Returns
True when the edit was accepted.
Definition at line 68 of file ModelPartList.cpp.
References index(), ModelPart::set(), and ModelPart::setVisible().
Member Data Documentation
rootItem
ModelPart* ModelPartList::rootItem private
Invisible root node that owns the entire ModelPart tree.
Definition at line 134 of file ModelPartList.h.
Referenced by appendChild(), columnCount(), getRootItem(), headerData(), index(), ModelPartList(), parent(), rowCount(), and ~ModelPartList().
The documentation for this class was generated from the following files:
ModelPartList.h
ModelPartList.cpp