VR Model Viewer: VRRenderThread Class Reference
VRRenderThread Class Reference
Runs the VTK/OpenVR scene on a worker thread.
#include <VRRenderThread.h>
Classes
struct PendingAppearance
Queued actor appearance update applied inside the VR thread.
struct PendingGeometry
Queued mesh update applied inside the VR thread.
struct TrackedActor
Stores one VR actor and its desktop/VR transform mapping state.
Public Types
enum Command {
PAUSE_RENDER , END_RENDER , ROTATE_X , ROTATE_Y ,
ROTATE_Z , RESET_VIEW , SET_VIEW_MODE , SET_SHOWCASE_SPIN
}
Thread-safe commands accepted by issueCommand().
enum ViewMode { STANDING_VIEW = 0 , SITTING_VIEW = 1 }
Starting height preset for the VR camera.
Signals
void actorTransformChanged (const QString &partId, double px, double py, double pz, double rx, double ry, double rz, double scale)
Emitted when a tracked VR actor has been moved in the headset.
void actorColorChanged (const QString &partId, int r, int g, int b)
Emitted when a controller action changes a tracked actor colour.
Public Member Functions
VRRenderThread (QObject *parent=nullptr)
Constructs the VR rendering thread.
~VRRenderThread ()
Requests shutdown and waits briefly for VR resources to release.
void addActorOffline (vtkActor *actor)
Adds an untracked actor before the VR thread starts.
void addActorOffline (const QString &partId, vtkActor *actor)
Adds a tracked actor before the VR thread starts.
void setSceneBounds (const double bounds[6])
Sets desktop-space model bounds used to scale and place the VR scene.
void setViewMode (ViewMode mode)
Sets the headset height preset.
void setViewYawDegrees (double yawDegrees)
Sets the yaw angle used when resetting the VR view.
void setViewTuning (double modelSizeMeters, double distanceMeters, double heightOffsetMeters)
Sets user-adjustable VR inspection scale and offset values.
void setEnvironmentPath (const QString &path)
Sets the HDR environment path used by the VR renderer.
void setEnvironmentOrientation (double tiltXDegrees, double tiltYDegrees, double headingDegrees)
Sets HDR orientation controls.
void setActorAppearance (const QString &partId, int r, int g, int b, bool visible, bool glowEnabled, int glowR, int glowG, int glowB)
Queues a safe appearance update for a tracked VR actor.
void setActorGeometry (const QString &partId, vtkPolyData *geometry)
Queues a safe geometry update for a tracked VR actor.
void issueCommand (int cmd, double value)
Queues a control command for the VR event loop.
Protected Member Functions
void run () override
Builds the OpenVR scene and runs the VR event loop.
Private Member Functions
void detectActorTransformChanges ()
Detects actor motion in VR and emits desktop transform updates.
void applyViewPose ()
Resets the physical VR camera pose using current view settings.
void configureEnvironment ()
Loads or clears the VR HDR environment.
void applyEnvironmentOrientation ()
Applies HDR tilt and heading to the active environment texture.
void applyPendingAppearances (const QVector< PendingAppearance > &appearances)
Applies queued appearance updates to tracked actors.
void applyPendingGeometries (const QVector< PendingGeometry > &geometries)
Applies queued geometry snapshots to tracked actor mappers.
void updateVrInspectionTransform ()
Recomputes desktop-to-VR scale and mapped scene bounds.
void captureDesktopTransform (TrackedActor &tracked)
Stores an actor transform in desktop space.
void rememberCurrentVrTransform (TrackedActor &tracked)
Stores the current VR-space actor transform as the change-detection baseline.
void applyVrInspectionTransform (TrackedActor &tracked)
Maps a tracked desktop transform into VR space and applies it to the actor.
void mapVrTransformToDesktop (const double vrPosition[3], const double vrOrientation[3], double vrScale, double desktopPosition[3], double desktopOrientation[3], double &desktopScale) const
Converts a VR-space transform back into desktop-space values.
void handleControllerColorAction (vtkEventData *eventData)
Handles controller colour-cycling for the currently picked actor.
QString partIdForActor (vtkActor *actor) const
Looks up the tracked ModelPart id for a VR actor.
Private Attributes
vtkSmartPointer< vtkOpenVRRenderWindow > window
OpenVR render window owned by the worker thread.
vtkSmartPointer< vtkOpenVRRenderWindowInteractor > interactor
OpenVR interactor processing headset/controller events.
vtkSmartPointer< vtkOpenVRRenderer > renderer
VR renderer for actors, skybox, lights, and camera.
vtkSmartPointer< vtkOpenVRCamera > camera
Active OpenVR camera.
vtkSmartPointer< vtkSkybox > environmentSkybox
Spherical skybox actor for HDR backgrounds.
vtkSmartPointer< vtkTexture > environmentTexture
Texture used for image-based lighting and skybox.
vtkSmartPointer< vtkImageData > environmentBaseImage
Tonemapped HDR image before orientation adjustment.
vtkSmartPointer< vtkImageData > environmentImage
Oriented HDR image currently bound to the texture.
QMutex mutex
Protects command flags and queued updates.
QWaitCondition condition
Wakes the render loop after queued state changes.
vtkSmartPointer< vtkActorCollection > actors
Actors added before the VR renderer starts.
QVector< TrackedActor > trackedActors
Tracked actor records for transform and colour callbacks.
QVector< PendingAppearance > pendingAppearances
Appearance updates waiting for the VR loop.
QVector< PendingGeometry > pendingGeometries
Geometry updates waiting for the VR loop.
std::chrono::time_point< std::chrono::steady_clock > t_last
Time of the previous animation update.
bool endRender = false
True when the render loop should stop.
double rotateX = 0.0
Continuous X rotation per animation step.
double rotateY = 0.0
Continuous Y rotation per animation step.
double rotateZ = 0.0
Continuous Z rotation per animation step.
bool isPaused = false
True when automatic animation is paused.
bool viewResetPending = false
True when applyViewPose() should run.
bool vrRemapPending = false
True when desktop bounds/scale changed.
bool environmentChangedPending = false
True when HDR path changed.
bool environmentOrientationPending = false
True when HDR orientation changed.
bool sceneBoundsValid = false
True after valid model bounds are supplied.
bool showcaseSpin = false
True when showcase spin animation is active.
QString environmentPath
Current HDR file path, or empty for gradient background.
double environmentTiltDegrees = 0.0
HDR X tilt in degrees.
double environmentTiltYDegrees = 0.0
HDR Y tilt in degrees.
double environmentHeadingDegrees = 0.0
HDR heading rotation in degrees.
ViewMode viewMode = STANDING_VIEW
Active standing/sitting view preset.
double viewYawDegrees = 28.0
Reset-view yaw angle around the model.
double viewModelSizeMeters = 2.4
Target largest model dimension in VR metres.
double viewDistanceMeters = 1.1
Extra standoff distance from the model.
double viewHeightOffsetMeters = 0.0
User height adjustment in metres.
double sceneBounds [6] = { -500.0, 500.0, -500.0, 500.0, 0.0, 1000.0 }
Desktop-space model bounds.
double desktopCenter [3] = { 0.0, 0.0, 0.0 }
Desktop-space centre used for VR mapping.
double vrBaseCenter [3] = { 0.0, 2.25, 0.0 }
VR-space target centre for the model.
double vrSceneBounds [6] = { -1.2, 1.2, 1.05, 3.45, 0.0, 1.2 }
VR-space mapped scene bounds.
double vrWorldScale = 0.001
Conversion scale from desktop units to VR metres.
Detailed Description
Runs the VTK/OpenVR scene on a worker thread.
The desktop renderer and the VR renderer cannot safely share live VTK pipeline objects while filters are being changed. This class therefore receives actor and geometry snapshots before or during VR rendering, applies queued changes inside run(), and emits desktop-space transform/colour updates back to MainWindow.
Definition at line 46 of file VRRenderThread.h.
Member Enumeration Documentation
Command
enum VRRenderThread::Command
Thread-safe commands accepted by issueCommand().
Enumerator
PAUSE_RENDER
Pause or resume continuous VR animation.
END_RENDER
Request the VR event loop to stop.
ROTATE_X
Set continuous X rotation speed.
ROTATE_Y
Set continuous Y rotation speed.
ROTATE_Z
Set continuous Z rotation speed.
RESET_VIEW
Reset the user view to the configured inspection pose.
SET_VIEW_MODE
Switch between standing and sitting view mode.
SET_SHOWCASE_SPIN
Enable or disable automatic showcase rotation.
Definition at line 55 of file VRRenderThread.h.
ViewMode
enum VRRenderThread::ViewMode
Starting height preset for the VR camera.
Enumerator
STANDING_VIEW
Standing headset height preset.
SITTING_VIEW
Sitting headset height preset.
Definition at line 70 of file VRRenderThread.h.
Constructor & Destructor Documentation
VRRenderThread()
VRRenderThread::VRRenderThread (QObject * parent = nullptr)
Constructs the VR rendering thread.
VRRenderThread constructor.
Parameters
parent Optional QObject parent for Qt ownership.
Initializes common state variables. Note: The VR Interactor loop blocks the thread, hence it must run in this dedicated thread rather than the GUI thread.
Definition at line 199 of file VRRenderThread.cpp.
References actors.
~VRRenderThread()
VRRenderThread::~VRRenderThread ()
Requests shutdown and waits briefly for VR resources to release.
Destructor.
Ensures proper cleanup of resources to prevent memory leaks during start/stop cycles.
Definition at line 208 of file VRRenderThread.cpp.
References END_RENDER, and issueCommand().
Member Function Documentation
actorColorChanged
void VRRenderThread::actorColorChanged (const QString & partId, int r, int g, int b) signal
Emitted when a controller action changes a tracked actor colour.
Parameters
partId Stable ModelPart identifier.
r Red channel in the range 0-255.
g Green channel in the range 0-255.
b Blue channel in the range 0-255.
Referenced by handleControllerColorAction(), and MainWindow::on_actionStart_VR_triggered().
actorTransformChanged
void VRRenderThread::actorTransformChanged (const QString & partId, double px, double py, double pz, double rx, double ry, double rz, double scale) signal
Emitted when a tracked VR actor has been moved in the headset.
Parameters
partId Stable ModelPart identifier.
px Desktop-space X position.
py Desktop-space Y position.
pz Desktop-space Z position.
rx Desktop-space X rotation in degrees.
ry Desktop-space Y rotation in degrees.
rz Desktop-space Z rotation in degrees.
scale Desktop-space uniform scale.
Referenced by detectActorTransformChanges(), and MainWindow::on_actionStart_VR_triggered().
addActorOffline() [1/2]
void VRRenderThread::addActorOffline (const QString & partId, vtkActor * actor)
Adds a tracked actor before the VR thread starts.
Parameters
partId Stable ModelPart identifier used for callbacks.
actor Detached actor copy to show in VR.
Definition at line 220 of file VRRenderThread.cpp.
References VRRenderThread::TrackedActor::actor, actors, captureDesktopTransform(), VRRenderThread::TrackedActor::partId, and trackedActors.
addActorOffline() [2/2]
void VRRenderThread::addActorOffline (vtkActor * actor)
Adds an untracked actor before the VR thread starts.
Adds an actor to the internal collection while the thread is not yet running.
Parameters
actor Actor to show in VR.
Definition at line 216 of file VRRenderThread.cpp.
References addActorOffline().
Referenced by addActorOffline(), and MainWindow::collectActorsForVR().
applyEnvironmentOrientation()
void VRRenderThread::applyEnvironmentOrientation () private
Applies HDR tilt and heading to the active environment texture.
Definition at line 740 of file VRRenderThread.cpp.
References environmentBaseImage, environmentHeadingDegrees, environmentImage, environmentSkybox, environmentTexture, environmentTiltDegrees, environmentTiltYDegrees, mutex, and renderer.
Referenced by configureEnvironment(), and run().
applyPendingAppearances()
void VRRenderThread::applyPendingAppearances (const QVector< PendingAppearance > & appearances) private
Applies queued appearance updates to tracked actors.
Parameters
appearances Updates copied from the protected queue.
Definition at line 773 of file VRRenderThread.cpp.
References trackedActors, and window.
Referenced by run().
applyPendingGeometries()
void VRRenderThread::applyPendingGeometries (const QVector< PendingGeometry > & geometries) private
Applies queued geometry snapshots to tracked actor mappers.
Parameters
geometries Geometry updates copied from the protected queue.
Definition at line 820 of file VRRenderThread.cpp.
References trackedActors, and window.
Referenced by run().
applyViewPose()
void VRRenderThread::applyViewPose () private
Resets the physical VR camera pose using current view settings.
Definition at line 593 of file VRRenderThread.cpp.
References camera, mutex, renderer, SITTING_VIEW, STANDING_VIEW, viewDistanceMeters, viewHeightOffsetMeters, viewMode, viewYawDegrees, vrSceneBounds, and window.
Referenced by run().
applyVrInspectionTransform()
void VRRenderThread::applyVrInspectionTransform (TrackedActor & tracked) private
Maps a tracked desktop transform into VR space and applies it to the actor.
Parameters
tracked Actor record to update.
Definition at line 925 of file VRRenderThread.cpp.
References VRRenderThread::TrackedActor::actor, captureDesktopTransform(), desktopCenter, VRRenderThread::TrackedActor::desktopOrientation, VRRenderThread::TrackedActor::desktopPosition, VRRenderThread::TrackedActor::desktopScale, VRRenderThread::TrackedActor::desktopTransformValid, rememberCurrentVrTransform(), vrBaseCenter, VRRenderThread::TrackedActor::vrTransformApplied, and vrWorldScale.
Referenced by run(), setSceneBounds(), and setViewTuning().
captureDesktopTransform()
void VRRenderThread::captureDesktopTransform (TrackedActor & tracked) private
Stores an actor transform in desktop space.
Parameters
tracked Actor record to update.
Definition at line 876 of file VRRenderThread.cpp.
References VRRenderThread::TrackedActor::actor, VRRenderThread::TrackedActor::desktopOrientation, VRRenderThread::TrackedActor::desktopPosition, VRRenderThread::TrackedActor::desktopScale, VRRenderThread::TrackedActor::desktopTransformValid, mapVrTransformToDesktop(), and VRRenderThread::TrackedActor::vrTransformApplied.
Referenced by addActorOffline(), applyVrInspectionTransform(), run(), setSceneBounds(), and setViewTuning().
configureEnvironment()
void VRRenderThread::configureEnvironment () private
Loads or clears the VR HDR environment.
Definition at line 676 of file VRRenderThread.cpp.
References applyEnvironmentOrientation(), environmentBaseImage, environmentImage, environmentPath, environmentSkybox, environmentTexture, mutex, and renderer.
Referenced by run().
detectActorTransformChanges()
void VRRenderThread::detectActorTransformChanges () private
Detects actor motion in VR and emits desktop transform updates.
Definition at line 961 of file VRRenderThread.cpp.
References actorTransformChanged(), mapVrTransformToDesktop(), mutex, showcaseSpin, and trackedActors.
Referenced by run().
handleControllerColorAction()
void VRRenderThread::handleControllerColorAction (vtkEventData * eventData) private
Handles controller colour-cycling for the currently picked actor.
Parameters
eventData VTK controller event data from OpenVR.
Definition at line 1050 of file VRRenderThread.cpp.
References actorColorChanged(), partIdForActor(), and renderer.
Referenced by run().
issueCommand()
void VRRenderThread::issueCommand (int cmd, double value)
Queues a control command for the VR event loop.
Interface to update rendering state or transformation parameters from the GUI thread.
Parameters
cmd Command value from Command.
value Numeric command payload, such as speed or boolean state.
Definition at line 350 of file VRRenderThread.cpp.
References condition, END_RENDER, endRender, isPaused, mutex, PAUSE_RENDER, RESET_VIEW, ROTATE_X, ROTATE_Y, ROTATE_Z, rotateX, rotateY, rotateZ, SET_SHOWCASE_SPIN, SET_VIEW_MODE, showcaseSpin, SITTING_VIEW, STANDING_VIEW, viewMode, and viewResetPending.
Referenced by MainWindow::configureActions(), MainWindow::on_actionPause_VR_triggered(), MainWindow::on_actionStart_VR_triggered(), MainWindow::resetVrView(), MainWindow::stopVRThread(), and ~VRRenderThread().
mapVrTransformToDesktop()
void VRRenderThread::mapVrTransformToDesktop (const double vrPosition[3], const double vrOrientation[3], double vrScale, double desktopPosition[3], double desktopOrientation[3], double & desktopScale) const private
Converts a VR-space transform back into desktop-space values.
Parameters
vrPosition VR-space XYZ position.
vrOrientation VR-space XYZ orientation in degrees.
vrScale VR-space uniform scale.
desktopPosition Output desktop-space position.
desktopOrientation Output desktop-space orientation.
desktopScale Output desktop-space uniform scale.
Definition at line 949 of file VRRenderThread.cpp.
References desktopCenter, vrBaseCenter, and vrWorldScale.
Referenced by captureDesktopTransform(), and detectActorTransformChanges().
partIdForActor()
QString VRRenderThread::partIdForActor (vtkActor * actor) const private
Looks up the tracked ModelPart id for a VR actor.
Parameters
actor Actor selected by the VR picker.
Returns
Part id, or an empty string when actor is not tracked.
Definition at line 1035 of file VRRenderThread.cpp.
References trackedActors.
Referenced by handleControllerColorAction().
rememberCurrentVrTransform()
void VRRenderThread::rememberCurrentVrTransform (TrackedActor & tracked) private
Stores the current VR-space actor transform as the change-detection baseline.
Parameters
tracked Actor record to update.
Definition at line 904 of file VRRenderThread.cpp.
References VRRenderThread::TrackedActor::actor, VRRenderThread::TrackedActor::initialized, VRRenderThread::TrackedActor::lastOrientation, VRRenderThread::TrackedActor::lastPosition, and VRRenderThread::TrackedActor::lastScale.
Referenced by applyVrInspectionTransform().
run()
void VRRenderThread::run () override protected
Builds the OpenVR scene and runs the VR event loop.
Main execution loop for the VR thread.
Triggered by VRRenderThread::start().
Definition at line 394 of file VRRenderThread.cpp.
References actors, applyEnvironmentOrientation(), applyPendingAppearances(), applyPendingGeometries(), applyViewPose(), applyVrInspectionTransform(), camera, captureDesktopTransform(), configureEnvironment(), detectActorTransformChanges(), endRender, environmentChangedPending, environmentOrientationPending, handleControllerColorAction(), interactor, isPaused, mutex, pendingAppearances, pendingGeometries, renderer, rotateX, rotateY, rotateZ, showcaseSpin, t_last, trackedActors, updateVrInspectionTransform(), viewResetPending, vrRemapPending, and window.
setActorAppearance()
void VRRenderThread::setActorAppearance (const QString & partId, int r, int g, int b, bool visible, bool glowEnabled, int glowR, int glowG, int glowB)
Queues a safe appearance update for a tracked VR actor.
Parameters
partId Stable ModelPart identifier.
r Base colour red channel.
g Base colour green channel.
b Base colour blue channel.
visible True to show the actor.
glowEnabled True to apply glow material settings.
glowR Glow red channel.
glowG Glow green channel.
glowB Glow blue channel.
Definition at line 311 of file VRRenderThread.cpp.
References VRRenderThread::PendingAppearance::b, condition, VRRenderThread::PendingAppearance::g, VRRenderThread::PendingAppearance::glowB, VRRenderThread::PendingAppearance::glowEnabled, VRRenderThread::PendingAppearance::glowG, VRRenderThread::PendingAppearance::glowR, mutex, VRRenderThread::PendingAppearance::partId, pendingAppearances, VRRenderThread::PendingAppearance::r, and VRRenderThread::PendingAppearance::visible.
setActorGeometry()
void VRRenderThread::setActorGeometry (const QString & partId, vtkPolyData * geometry)
Queues a safe geometry update for a tracked VR actor.
Parameters
partId Stable ModelPart identifier.
geometry Deep-copied polydata snapshot to install in the VR mapper.
Definition at line 333 of file VRRenderThread.cpp.
References condition, VRRenderThread::PendingGeometry::geometry, mutex, VRRenderThread::PendingGeometry::partId, and pendingGeometries.
setEnvironmentOrientation()
void VRRenderThread::setEnvironmentOrientation (double tiltXDegrees, double tiltYDegrees, double headingDegrees)
Sets HDR orientation controls.
Parameters
tiltXDegrees X-axis tilt in degrees.
tiltYDegrees Y-axis tilt in degrees.
headingDegrees Heading rotation in degrees.
Definition at line 301 of file VRRenderThread.cpp.
References condition, environmentHeadingDegrees, environmentOrientationPending, environmentTiltDegrees, environmentTiltYDegrees, and mutex.
Referenced by MainWindow::applyEnvironmentOrientation(), and MainWindow::on_actionStart_VR_triggered().
setEnvironmentPath()
void VRRenderThread::setEnvironmentPath (const QString & path)
Sets the HDR environment path used by the VR renderer.
Parameters
path Absolute or application-relative HDR file path; empty uses gradient background.
Definition at line 293 of file VRRenderThread.cpp.
References condition, environmentChangedPending, environmentPath, and mutex.
Referenced by MainWindow::applyEnvironmentSelection(), and MainWindow::on_actionStart_VR_triggered().
setSceneBounds()
void VRRenderThread::setSceneBounds (const double bounds[6])
Sets desktop-space model bounds used to scale and place the VR scene.
Parameters
bounds Bounds array in VTK order: xmin, xmax, ymin, ymax, zmin, zmax.
Definition at line 232 of file VRRenderThread.cpp.
References applyVrInspectionTransform(), captureDesktopTransform(), condition, mutex, sceneBounds, sceneBoundsValid, trackedActors, updateVrInspectionTransform(), viewResetPending, and vrRemapPending.
Referenced by MainWindow::on_actionStart_VR_triggered(), and MainWindow::resetVrView().
setViewMode()
void VRRenderThread::setViewMode (ViewMode mode)
Sets the headset height preset.
Parameters
mode Standing or sitting view mode.
Definition at line 255 of file VRRenderThread.cpp.
References condition, mutex, viewMode, and viewResetPending.
Referenced by MainWindow::on_actionStart_VR_triggered(), MainWindow::resetVrView(), and MainWindow::setupProfessionalUi().
setViewTuning()
void VRRenderThread::setViewTuning (double modelSizeMeters, double distanceMeters, double heightOffsetMeters)
Sets user-adjustable VR inspection scale and offset values.
Parameters
modelSizeMeters Desired largest model dimension in metres.
distanceMeters Extra distance from the model after reset.
heightOffsetMeters Vertical headset adjustment in metres.
Definition at line 271 of file VRRenderThread.cpp.
References applyVrInspectionTransform(), captureDesktopTransform(), condition, mutex, trackedActors, updateVrInspectionTransform(), viewDistanceMeters, viewHeightOffsetMeters, viewModelSizeMeters, viewResetPending, and vrRemapPending.
Referenced by MainWindow::applyVrTuningToThread(), MainWindow::on_actionStart_VR_triggered(), and MainWindow::resetVrView().
setViewYawDegrees()
void VRRenderThread::setViewYawDegrees (double yawDegrees)
Sets the yaw angle used when resetting the VR view.
Parameters
yawDegrees View yaw in degrees around the car.
Definition at line 263 of file VRRenderThread.cpp.
References condition, mutex, viewResetPending, and viewYawDegrees.
Referenced by MainWindow::on_actionStart_VR_triggered(), MainWindow::resetVrView(), and MainWindow::setupProfessionalUi().
updateVrInspectionTransform()
void VRRenderThread::updateVrInspectionTransform () private
Recomputes desktop-to-VR scale and mapped scene bounds.
Definition at line 852 of file VRRenderThread.cpp.
References desktopCenter, sceneBounds, viewModelSizeMeters, vrBaseCenter, vrSceneBounds, and vrWorldScale.
Referenced by run(), setSceneBounds(), and setViewTuning().
Member Data Documentation
actors
vtkSmartPointer<vtkActorCollection> VRRenderThread::actors private
Actors added before the VR renderer starts.
Definition at line 210 of file VRRenderThread.h.
Referenced by addActorOffline(), run(), and VRRenderThread().
camera
vtkSmartPointer<vtkOpenVRCamera> VRRenderThread::camera private
Active OpenVR camera.
Definition at line 202 of file VRRenderThread.h.
Referenced by applyViewPose(), and run().
condition
QWaitCondition VRRenderThread::condition private
Wakes the render loop after queued state changes.
Definition at line 209 of file VRRenderThread.h.
Referenced by issueCommand(), setActorAppearance(), setActorGeometry(), setEnvironmentOrientation(), setEnvironmentPath(), setSceneBounds(), setViewMode(), setViewTuning(), and setViewYawDegrees().
desktopCenter
double VRRenderThread::desktopCenter[3] = { 0.0, 0.0, 0.0 } private
Desktop-space centre used for VR mapping.
Definition at line 280 of file VRRenderThread.h.
Referenced by applyVrInspectionTransform(), mapVrTransformToDesktop(), and updateVrInspectionTransform().
endRender
bool VRRenderThread::endRender = false private
True when the render loop should stop.
Definition at line 259 of file VRRenderThread.h.
Referenced by issueCommand(), and run().
environmentBaseImage
vtkSmartPointer<vtkImageData> VRRenderThread::environmentBaseImage private
Tonemapped HDR image before orientation adjustment.
Definition at line 205 of file VRRenderThread.h.
Referenced by applyEnvironmentOrientation(), and configureEnvironment().
environmentChangedPending
bool VRRenderThread::environmentChangedPending = false private
True when HDR path changed.
Definition at line 266 of file VRRenderThread.h.
Referenced by run(), and setEnvironmentPath().
environmentHeadingDegrees
double VRRenderThread::environmentHeadingDegrees = 0.0 private
HDR heading rotation in degrees.
Definition at line 273 of file VRRenderThread.h.
Referenced by applyEnvironmentOrientation(), and setEnvironmentOrientation().
environmentImage
vtkSmartPointer<vtkImageData> VRRenderThread::environmentImage private
Oriented HDR image currently bound to the texture.
Definition at line 206 of file VRRenderThread.h.
Referenced by applyEnvironmentOrientation(), and configureEnvironment().
environmentOrientationPending
bool VRRenderThread::environmentOrientationPending = false private
True when HDR orientation changed.
Definition at line 267 of file VRRenderThread.h.
Referenced by run(), and setEnvironmentOrientation().
environmentPath
QString VRRenderThread::environmentPath private
Current HDR file path, or empty for gradient background.
Definition at line 270 of file VRRenderThread.h.
Referenced by configureEnvironment(), and setEnvironmentPath().
environmentSkybox
vtkSmartPointer<vtkSkybox> VRRenderThread::environmentSkybox private
Spherical skybox actor for HDR backgrounds.
Definition at line 203 of file VRRenderThread.h.
Referenced by applyEnvironmentOrientation(), and configureEnvironment().
environmentTexture
vtkSmartPointer<vtkTexture> VRRenderThread::environmentTexture private
Texture used for image-based lighting and skybox.
Definition at line 204 of file VRRenderThread.h.
Referenced by applyEnvironmentOrientation(), and configureEnvironment().
environmentTiltDegrees
double VRRenderThread::environmentTiltDegrees = 0.0 private
HDR X tilt in degrees.
Definition at line 271 of file VRRenderThread.h.
Referenced by applyEnvironmentOrientation(), and setEnvironmentOrientation().
environmentTiltYDegrees
double VRRenderThread::environmentTiltYDegrees = 0.0 private
HDR Y tilt in degrees.
Definition at line 272 of file VRRenderThread.h.
Referenced by applyEnvironmentOrientation(), and setEnvironmentOrientation().
interactor
vtkSmartPointer<vtkOpenVRRenderWindowInteractor> VRRenderThread::interactor private
OpenVR interactor processing headset/controller events.
Definition at line 200 of file VRRenderThread.h.
Referenced by run().
isPaused
bool VRRenderThread::isPaused = false private
True when automatic animation is paused.
Definition at line 263 of file VRRenderThread.h.
Referenced by issueCommand(), and run().
mutex
QMutex VRRenderThread::mutex private
Protects command flags and queued updates.
Definition at line 208 of file VRRenderThread.h.
Referenced by applyEnvironmentOrientation(), applyViewPose(), configureEnvironment(), detectActorTransformChanges(), issueCommand(), run(), setActorAppearance(), setActorGeometry(), setEnvironmentOrientation(), setEnvironmentPath(), setSceneBounds(), setViewMode(), setViewTuning(), and setViewYawDegrees().
pendingAppearances
QVector<PendingAppearance> VRRenderThread::pendingAppearances private
Appearance updates waiting for the VR loop.
Definition at line 246 of file VRRenderThread.h.
Referenced by run(), and setActorAppearance().
pendingGeometries
QVector<PendingGeometry> VRRenderThread::pendingGeometries private
Geometry updates waiting for the VR loop.
Definition at line 256 of file VRRenderThread.h.
Referenced by run(), and setActorGeometry().
renderer
vtkSmartPointer<vtkOpenVRRenderer> VRRenderThread::renderer private
VR renderer for actors, skybox, lights, and camera.
Definition at line 201 of file VRRenderThread.h.
Referenced by applyEnvironmentOrientation(), applyViewPose(), configureEnvironment(), handleControllerColorAction(), and run().
rotateX
double VRRenderThread::rotateX = 0.0 private
Continuous X rotation per animation step.
Definition at line 260 of file VRRenderThread.h.
Referenced by issueCommand(), and run().
rotateY
double VRRenderThread::rotateY = 0.0 private
Continuous Y rotation per animation step.
Definition at line 261 of file VRRenderThread.h.
Referenced by issueCommand(), and run().
rotateZ
double VRRenderThread::rotateZ = 0.0 private
Continuous Z rotation per animation step.
Definition at line 262 of file VRRenderThread.h.
Referenced by issueCommand(), and run().
sceneBounds
double VRRenderThread::sceneBounds[6] = { -500.0, 500.0, -500.0, 500.0, 0.0, 1000.0 } private
Desktop-space model bounds.
Definition at line 279 of file VRRenderThread.h.
Referenced by setSceneBounds(), and updateVrInspectionTransform().
sceneBoundsValid
bool VRRenderThread::sceneBoundsValid = false private
True after valid model bounds are supplied.
Definition at line 268 of file VRRenderThread.h.
Referenced by setSceneBounds().
showcaseSpin
bool VRRenderThread::showcaseSpin = false private
True when showcase spin animation is active.
Definition at line 269 of file VRRenderThread.h.
Referenced by detectActorTransformChanges(), issueCommand(), and run().
t_last
std::chrono::time_point<std::chrono::steady_clock> VRRenderThread::t_last private
Time of the previous animation update.
Definition at line 258 of file VRRenderThread.h.
Referenced by run().
trackedActors
QVector<TrackedActor> VRRenderThread::trackedActors private
Tracked actor records for transform and colour callbacks.
Definition at line 229 of file VRRenderThread.h.
Referenced by addActorOffline(), applyPendingAppearances(), applyPendingGeometries(), detectActorTransformChanges(), partIdForActor(), run(), setSceneBounds(), and setViewTuning().
viewDistanceMeters
double VRRenderThread::viewDistanceMeters = 1.1 private
Extra standoff distance from the model.
Definition at line 277 of file VRRenderThread.h.
Referenced by applyViewPose(), and setViewTuning().
viewHeightOffsetMeters
double VRRenderThread::viewHeightOffsetMeters = 0.0 private
User height adjustment in metres.
Definition at line 278 of file VRRenderThread.h.
Referenced by applyViewPose(), and setViewTuning().
viewMode
ViewMode VRRenderThread::viewMode = STANDING_VIEW private
Active standing/sitting view preset.
Definition at line 274 of file VRRenderThread.h.
Referenced by applyViewPose(), issueCommand(), and setViewMode().
viewModelSizeMeters
double VRRenderThread::viewModelSizeMeters = 2.4 private
Target largest model dimension in VR metres.
Definition at line 276 of file VRRenderThread.h.
Referenced by setViewTuning(), and updateVrInspectionTransform().
viewResetPending
bool VRRenderThread::viewResetPending = false private
True when applyViewPose() should run.
Definition at line 264 of file VRRenderThread.h.
Referenced by issueCommand(), run(), setSceneBounds(), setViewMode(), setViewTuning(), and setViewYawDegrees().
viewYawDegrees
double VRRenderThread::viewYawDegrees = 28.0 private
Reset-view yaw angle around the model.
Definition at line 275 of file VRRenderThread.h.
Referenced by applyViewPose(), and setViewYawDegrees().
vrBaseCenter
double VRRenderThread::vrBaseCenter[3] = { 0.0, 2.25, 0.0 } private
VR-space target centre for the model.
Definition at line 281 of file VRRenderThread.h.
Referenced by applyVrInspectionTransform(), mapVrTransformToDesktop(), and updateVrInspectionTransform().
vrRemapPending
bool VRRenderThread::vrRemapPending = false private
True when desktop bounds/scale changed.
Definition at line 265 of file VRRenderThread.h.
Referenced by run(), setSceneBounds(), and setViewTuning().
vrSceneBounds
double VRRenderThread::vrSceneBounds[6] = { -1.2, 1.2, 1.05, 3.45, 0.0, 1.2 } private
VR-space mapped scene bounds.
Definition at line 282 of file VRRenderThread.h.
Referenced by applyViewPose(), and updateVrInspectionTransform().
vrWorldScale
double VRRenderThread::vrWorldScale = 0.001 private
Conversion scale from desktop units to VR metres.
Definition at line 283 of file VRRenderThread.h.
Referenced by applyVrInspectionTransform(), mapVrTransformToDesktop(), and updateVrInspectionTransform().
window
vtkSmartPointer<vtkOpenVRRenderWindow> VRRenderThread::window private
OpenVR render window owned by the worker thread.
Definition at line 199 of file VRRenderThread.h.
Referenced by applyPendingAppearances(), applyPendingGeometries(), applyViewPose(), and run().
The documentation for this class was generated from the following files:
VRRenderThread.h
VRRenderThread.cpp