name: doxygen-deploy

on:
  push:
    branches: [master, main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy-ws6-documentation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Doxygen
        run: sudo apt-get update && sudo apt-get install -y doxygen

      - name: Run Doxygen
        working-directory: ${{ github.workspace }}/team/WS6
        run: doxygen Doxyfile

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: ${{ github.workspace }}/team/WS6/html
          clean: true
